// Ported from: src/Kusto.Language/Parser/CodeGen/AriaBridgeCommands.tt
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Upstream license: Apache-2.0, Copyright (c) 2019 Microsoft Corporation.
// This file is a derived work; see NOTICE. Modifications are marked "// PORT:".

package org.graylog.kusto.language;

import java.util.List;

import org.graylog.kusto.language.symbols.CommandSymbol;

// PORT: §8 stub. The upstream file is generated by T4 from AriaBridgeCommandInfos (excluded command generator inputs); the generated
// command symbols are out of scope for Graylog. Only the list read by GlobalState.getCommands is kept, and it is empty.
public final class AriaBridgeCommands
{
    private AriaBridgeCommands()
    {
    }

    public static final List<CommandSymbol> All = List.of();
}
