// Ported from: src/Kusto.Language/Symbols/FunctionSymbol.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Upstream license: Apache-2.0, Copyright (c) 2019 Microsoft Corporation.
// This file is a derived work; see NOTICE. Modifications are marked "// PORT:".
package org.graylog.kusto.language.symbols;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import org.graylog.kusto.language.GlobalState;
import org.graylog.kusto.language.syntax.FunctionBody;
import org.graylog.kusto.language.utils.ArgumentCheckers;
import org.graylog.kusto.language.utils.ListExtensions;
import org.graylog.kusto.language.utils.Optional;

/// <summary>
/// The symbol for a function.
/// </summary>
public final class FunctionSymbol extends TypeSymbol
{
    @Override
    public SymbolKind kind() { return SymbolKind.Function; }

    /// <summary>
    /// A function can have one or more signatures.
    /// </summary>
    private final List<Signature> signatures;
    public List<Signature> signatures() { return this.signatures; }

    /// <summary>
    /// The description of the function.
    /// </summary>
    private final String description;
    public String description() { return this.description; }

    /// <summary>
    /// How the name of the result of this function is determined.
    /// </summary>
    private final ResultNameKind resultNameKind;
    public ResultNameKind resultNameKind() { return this.resultNameKind; }

    /// <summary>
    /// The prefix to column names generated by this function.
    /// </summary>
    private final String resultNamePrefix;
    public String resultNamePrefix() { return this.resultNamePrefix; }

    /// <summary>
    /// The name of an alternative function to use instead of this function
    /// if this function is obsolete/deprecated.
    /// </summary>
    private final String alternative;
    public String alternative() { return this.alternative; }

    /// <summary>
    /// True if this function is considered obsolete/deprecated.
    /// </summary>
    public boolean isObsolete() { return alternative() != null; }

    /// <summary>
    /// The name of an alternative more optimized function to use
    /// instead of this function when possible.
    /// </summary>
    private final String optimizedAlternative;
    public String optimizedAlternative() { return this.optimizedAlternative; }

    /// <summary>
    /// A function that determines when this function is available in a given context.
    /// </summary>
    private final CustomAvailability customAvailability;
    public CustomAvailability customAvailability() { return this.customAvailability; }

    // [Flags]
    private static final class FunctionFlags // PORT: §3.17 [Flags] enum → int constants holder (D23)
    {
        private FunctionFlags() // PORT: §3.17
        {
        }

        static final int None     = 0b0000_0000;
        static final int Hidden   = 0b0000_0001;
        static final int Foldable = 0b0000_0010;
        static final int View     = 0b0000_0100;
    }

    /// <summary>
    /// Function internal state bit flags.
    /// </summary>
    private final int _flags; // PORT: §3.17 FunctionFlags

    /// <summary>
    /// If true, the symbol is hidden from Intellisense.
    /// </summary>
    @Override
    public boolean isHidden() { return (_flags & FunctionFlags.Hidden) != 0 || super.isHidden(); }

    /// <summary>
    /// If true this function is considered a constant when all its arguments are constants.
    /// </summary>
    public boolean isConstantFoldable() { return (_flags & FunctionFlags.Foldable) != 0; }

    /// <summary>
    /// If true, this function is considered a view.
    /// Views are local functions that can be accessed using the table() function.
    /// </summary>
    public boolean isView() { return (_flags & FunctionFlags.View) != 0; }

    private FunctionSymbol(
        String name,
        Iterable<Signature> signatures,
        int flags, // PORT: §3.17 FunctionFlags
        ResultNameKind resultNameKind,
        String resultNamePrefix,
        String description,
        String alternative,
        String optimizedAlternative,
        CustomAvailability fnAvailability)
    {
        super(name);
        this.signatures = ArgumentCheckers.checkArgumentNullOrEmptyOrElementNull(ListExtensions.toReadOnly(signatures), "signatures"); // PORT: §3.5
        this.description = description != null ? description : ""; // PORT: §3.14 ??

        for (var signature : this.signatures())
        {
            signature.setSymbol(this);
        }

        _flags = flags;
        this.resultNameKind = resultNameKind;
        this.resultNamePrefix = resultNamePrefix;
        this.alternative = alternative;
        this.optimizedAlternative = optimizedAlternative;
        customAvailability = fnAvailability;
    }

    public FunctionSymbol(String name, Iterable<Signature> signatures, String description)
    {
        this(
            name,
            signatures,
            /*flags:*/ FunctionFlags.None,
            /*resultNameKind:*/ ResultNameKind.Default,
            /*resultNamePrefix:*/ null,
            /*description:*/ description,
            /*alternative:*/ null,
            /*optimizedAlternative:*/ null,
            /*fnAvailability:*/ null); // PORT: §3.12 named arguments → positional
    }

    public FunctionSymbol(String name, Iterable<Signature> signatures) // PORT: §3.12 description = null
    {
        this(name, signatures, (String) null);
    }

    public FunctionSymbol(String name, Signature... signatures)
    {
        this(name, (Iterable<Signature>) (signatures != null ? Arrays.asList(signatures) : null)); // PORT: §3.10 params array → List
    }

    public FunctionSymbol(String name, TypeSymbol returnType, List<Parameter> parameters, String description)
    {
        this(name, single(new Signature(returnType, parameters)), description); // PORT: §3.10 new[] { … } → List
    }

    public FunctionSymbol(String name, TypeSymbol returnType, List<Parameter> parameters) // PORT: §3.12 description = null
    {
        this(name, returnType, parameters, (String) null);
    }

    public FunctionSymbol(String name, TypeSymbol returnType, Parameter... parameters)
    {
        this(name, single(new Signature(returnType, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, ReturnTypeKind returnTypeKind, List<Parameter> parameters)
    {
        this(name, single(new Signature(returnTypeKind, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, ReturnTypeKind returnTypeKind, Parameter... parameters)
    {
        this(name, single(new Signature(returnTypeKind, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, CustomReturnType customReturnType, Tabularity tabularity, List<Parameter> parameters)
    {
        this(name, single(new Signature(customReturnType, tabularity, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, CustomReturnType customReturnType, Tabularity tabularity, Parameter... parameters)
    {
        this(name, single(new Signature(customReturnType, tabularity, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, String body, Tabularity tabularity, List<Parameter> parameters, String description)
    {
        this(name, single(new Signature(body, tabularity, parameters)), description); // PORT: §3.10
    }

    public FunctionSymbol(String name, String body, Tabularity tabularity, List<Parameter> parameters) // PORT: §3.12 description = null
    {
        this(name, body, tabularity, parameters, (String) null);
    }

    public FunctionSymbol(String name, String body, Tabularity tabularity, Parameter... parameters)
    {
        this(name, single(new Signature(body, tabularity, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, String body, List<Parameter> parameters, String description)
    {
        this(name, single(new Signature(body, Tabularity.Unspecified, parameters)), description); // PORT: §3.10
    }

    public FunctionSymbol(String name, String body, List<Parameter> parameters) // PORT: §3.12 description = null
    {
        this(name, body, parameters, (String) null);
    }

    public FunctionSymbol(String name, String body, Parameter... parameters)
    {
        this(name, single(new Signature(body, Tabularity.Unspecified, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, String parameterList, String body, String description)
    {
        this(name, single(new Signature(body, Tabularity.Unspecified, Parameter.parseList(parameterList))), description); // PORT: §3.10
    }

    public FunctionSymbol(String name, String parameterList, String body) // PORT: §3.12 description = null
    {
        this(name, parameterList, body, (String) null);
    }

    public FunctionSymbol(String name, String parameterList, String body, Tabularity tabularity, String description)
    {
        this(name, single(new Signature(body, tabularity, Parameter.parseList(parameterList))), description); // PORT: §3.10
    }

    public FunctionSymbol(String name, String parameterList, String body, Tabularity tabularity) // PORT: §3.12 description = null
    {
        this(name, parameterList, body, tabularity, (String) null);
    }

    public FunctionSymbol(String name, FunctionBody declaration, List<Parameter> parameters)
    {
        this(name, single(new Signature(declaration, parameters))); // PORT: §3.10
    }

    public FunctionSymbol(String name, FunctionBody declaration, Parameter... parameters)
    {
        this(name, single(new Signature(declaration, parameters))); // PORT: §3.10
    }

    // PORT: §3.10 `new[] { signature }` passed as IEnumerable<Signature>
    private static Iterable<Signature> single(Signature signature)
    {
        return Arrays.asList(signature);
    }

    /// <summary>
    /// Constructs a new <see cref="FunctionSymbol"/> if one of the arguments differs from the
    /// existing corresponding property value, or returns this instance if there are no differences.
    /// </summary>
    // PORT: §3.12 only the full signature: every caller passes one named argument and Optional.NONE() for the rest
    private FunctionSymbol with(
        Optional<String> name,
        Optional<Iterable<Signature>> signatures,
        Optional<Integer> flags, // PORT: §3.17 FunctionFlags
        Optional<ResultNameKind> resultNameKind,
        Optional<String> resultNamePrefix,
        Optional<String> description,
        Optional<String> alternative,
        Optional<String> optimizedAlternative,
        Optional<CustomAvailability> fnAvailability)
    {
        var newName = name.hasValue() ? name.value() : this.name();
        var newSignatures = signatures.hasValue() ? signatures.value() : this.signatures();
        var newFlags = flags.hasValue() ? flags.value().intValue() : _flags;
        var newResultNameKind = resultNameKind.hasValue() ? resultNameKind.value() : this.resultNameKind();
        var newResultNamePrefix = resultNamePrefix.hasValue() ? resultNamePrefix.value() : this.resultNamePrefix();
        var newDescription = description.hasValue() ? description.value() : this.description();
        var newAlternative = alternative.hasValue() ? alternative.value() : this.alternative();
        var newOptimizedAlternative = optimizedAlternative.hasValue() ? optimizedAlternative.value() : this.optimizedAlternative();
        var newFnAvailability = fnAvailability.hasValue() ? fnAvailability.value() : customAvailability();

        if (!Objects.equals(newName, this.name()) // PORT: §3.14 string ==
            || newSignatures != this.signatures() // reference comparison, as upstream (IEnumerable !=)
            || newFlags != this._flags
            || newResultNameKind != this.resultNameKind()
            || !Objects.equals(newResultNamePrefix, this.resultNamePrefix()) // PORT: §3.14 string ==
            || !Objects.equals(newDescription, this.description()) // PORT: §3.14 string ==
            || !Objects.equals(newAlternative, this.alternative()) // PORT: §3.14 string ==
            || !Objects.equals(newOptimizedAlternative, this.optimizedAlternative()) // PORT: §3.14 string ==
            || newFnAvailability != customAvailability()) // PORT: §3.8 delegate value equality → reference equality (Java lambdas have no value equality)
        {
            return new FunctionSymbol(
                newName,
                newSignatures,
                newFlags,
                newResultNameKind,
                newResultNamePrefix,
                newDescription,
                newAlternative,
                newOptimizedAlternative,
                newFnAvailability);
        }
        else
        {
            return this;
        }
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> that is hidden from completion lists.
    /// </summary>
    public FunctionSymbol hide()
    {
        return withIsHidden(true);
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="IsHidden"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withIsHidden(boolean isHidden)
    {
        return with(Optional.NONE(), Optional.NONE(), /*flags:*/ Optional.of(
            isHidden
                ? _flags | FunctionFlags.Hidden
                : _flags & ~FunctionFlags.Hidden), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> that is a constant if all its arguments are constant.
    /// </summary>
    public FunctionSymbol constantFoldable()
    {
        return withIsConstantFoldable(true);
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="IsConstantFoldable"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withIsConstantFoldable(boolean isConstantFoldable)
    {
        return with(Optional.NONE(), Optional.NONE(), /*flags:*/ Optional.of(
            isConstantFoldable
                ? _flags | FunctionFlags.Foldable
                : _flags & ~FunctionFlags.Foldable), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionFlags"/> with the <see cref="IsView"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withIsView(boolean isView)
    {
        return with(Optional.NONE(), Optional.NONE(), /*flags:*/ Optional.of(
            isView
                ? _flags | FunctionFlags.View
                : _flags & ~FunctionFlags.View), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="ResultNamePrefix"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withResultNamePrefix(String resultNamePrefix)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), /*resultNamePrefix:*/ Optional.of(resultNamePrefix), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="ResultNameKind"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withResultNameKind(ResultNameKind kind)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), /*resultNameKind:*/ Optional.of(kind), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="Description"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withDescription(String description)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), /*description:*/ Optional.of(description), Optional.NONE(), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> that is considered obsolete/deprecated.
    /// </summary>
    public FunctionSymbol obsolete(String alternative)
    {
        return withIsObsolete(true, alternative).hide();
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> with the <see cref="IsObsolete"/> property set to the specified value.
    /// </summary>
    public FunctionSymbol withIsObsolete(boolean isObsolete, String alternative)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), /*alternative:*/ Optional.of(isObsolete ? (alternative != null ? alternative : "") : null), Optional.NONE(), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional; §3.14 ??
    }

    public FunctionSymbol withIsObsolete(boolean isObsolete) // PORT: §3.12 alternative = null
    {
        return withIsObsolete(isObsolete, null);
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> that is considered to be less optimized
    /// than the alternative function.
    /// </summary>
    public FunctionSymbol withOptimizedAlternative(String alternative)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), /*optimizedAlternative:*/ Optional.of(alternative), Optional.NONE()); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// Creates a new <see cref="FunctionSymbol"/> that has a custom function determining whether or
    /// not the function is available in a given context.
    /// </summary>
    public FunctionSymbol withCustomAvailability(CustomAvailability fnAvailability)
    {
        return with(Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), Optional.NONE(), /*fnAvailability:*/ Optional.of(fnAvailability)); // PORT: §3.12; §3.8 implicit Optional
    }

    /// <summary>
    /// The tabularity of the function.
    /// </summary>
    @Override
    public Tabularity tabularity() { return this.signatures().get(0).tabularity(); }

    /// <summary>
    /// Gets the return type for the function as best as can be determined without specific call site arguments.
    /// </summary>
    public TypeSymbol getReturnType(GlobalState globals)
    {
        return this.signatures().get(0).getReturnType(globals);
    }

    /// <summary>
    /// The minimum number of arguments that this function requires.
    /// </summary>
    public int minArgumentCount()
    {
        var min = -1;

        for (var s : this.signatures())
        {
            min = (min == -1)
                ? s.minArgumentCount()
                : Math.min(min, s.minArgumentCount());
        }

        return min;
    }

    /// <summary>
    /// The maximum number of arguments this function can take.
    /// </summary>
    public int maxArgumentCount()
    {
        var max = -1;

        for (var s : this.signatures())
        {
            max = (max == -1)
                ? s.maxArgumentCount()
                : Math.max(max, s.maxArgumentCount());
        }

        return max;
    }

}
