// Ported from: src/Kusto.Language/Parser/CodeGen/EngineCommandGrammar.tt
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Upstream license: Apache-2.0, Copyright (c) 2019 Microsoft Corporation.
// This file is a derived work; see NOTICE. Modifications are marked "// PORT:".

package org.graylog.kusto.language.parsing;

import org.graylog.kusto.language.GlobalState;

// PORT: §8 stub. The upstream file is generated by T4 (CommandGenerator.GenerateParser over EngineCommandInfos); the generated
// command parsers are out of scope for Graylog. createCommandParsers is deliberately not overridden, so the base class
// supplies no command parsers and every command text parses as UnknownCommand (PORTING.md section 8, D10).
public class EngineCommandGrammar extends CommandGrammar
{
    public EngineCommandGrammar(GlobalState globals)
    {
        super(globals);
    }
}
