// Original to kusto-java (no upstream file). SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Graylog, Inc. Purpose: non-generic facade over Parsers<LexicalToken>, generated by kusto-language-generator (D7)
// GENERATED by kusto-language-generator (LexicalTokenParsersGenerator) from Parsers.java; do not edit.

package org.graylog.kusto.language.parsing;

import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

import org.graylog.kusto.language.utils.dotnet.EqualityComparer;
import org.graylog.kusto.language.utils.dotnet.Func3;
import org.graylog.kusto.language.utils.dotnet.Func4;
import org.graylog.kusto.language.utils.dotnet.Func5;
import org.graylog.kusto.language.utils.dotnet.Func6;
import org.graylog.kusto.language.utils.dotnet.Func7;
import org.graylog.kusto.language.utils.dotnet.Func8;
import org.graylog.kusto.language.utils.dotnet.Func9;

/**
 * The members of {@link Parsers} with {@code TInput} bound to {@link LexicalToken}, so grammar files can
 * {@code import static org.graylog.kusto.language.parsing.LexicalTokenParsers.*} in place of upstream's
 * {@code using static Parsers<LexicalToken>} (PORTING.md 3.10, D7). Every method delegates to the
 * {@code Parsers} method of the same name and parameters.
 */
public final class LexicalTokenParsers
{
    private LexicalTokenParsers()
    {
    }

    /** A parser that always consumes one input item, but produces nothing. */
    public static final Parser<LexicalToken> Any = Parsers.any();

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static Parser<LexicalToken> and(Parser<LexicalToken>... parsers)
    {
        return Parsers.<LexicalToken>and(parsers);
    }

    public static Parser<LexicalToken> any()
    {
        return Parsers.<LexicalToken>any();
    }

    public static <TLeft, TOutput> Parser2<LexicalToken, TOutput> apply(Parser2<LexicalToken, TLeft> leftParser, Function<Parsers.LeftValue<TLeft>, RightParser<LexicalToken, TOutput>> fnRightParser)
    {
        return Parsers.<LexicalToken, TLeft, TOutput>apply(leftParser, fnRightParser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> applyOptional(Parser2<LexicalToken, TOutput> leftParser, Function<Parsers.LeftValue<TOutput>, RightParser<LexicalToken, TOutput>> fnRightParser)
    {
        return Parsers.<LexicalToken, TOutput>applyOptional(leftParser, fnRightParser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> applyZeroOrMore(Parser2<LexicalToken, TOutput> leftParser, Function<Parsers.LeftValue<TOutput>, RightParser<LexicalToken, TOutput>> fnRightParser)
    {
        return Parsers.<LexicalToken, TOutput>applyZeroOrMore(leftParser, fnRightParser);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static Parser<LexicalToken> best(Parser<LexicalToken>... parsers)
    {
        return Parsers.<LexicalToken>best(parsers);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static <TOutput> Parser2<LexicalToken, TOutput> best(Parser2<LexicalToken, TOutput>... parsers)
    {
        return Parsers.<LexicalToken, TOutput>best(parsers);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> best(Parser2<LexicalToken, TOutput>[] parsers, BiPredicate<TOutput, TOutput> fnBetter)
    {
        return Parsers.<LexicalToken, TOutput>best(parsers, fnBetter);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static <TOutput> RightParser<LexicalToken, TOutput> best(RightParser<LexicalToken, TOutput>... parsers)
    {
        return Parsers.<LexicalToken, TOutput>best(parsers);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> convert(Parser<LexicalToken> pattern, SourceProducer<LexicalToken, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>convert(pattern, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> convertList(Parser<LexicalToken> pattern, Function<List<LexicalToken>, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>convertList(pattern, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> convert(Parser<LexicalToken> pattern, Function<LexicalToken, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>convert(pattern, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> convert(Parser<LexicalToken> pattern, TOutput value)
    {
        return Parsers.<LexicalToken, TOutput>convert(pattern, value);
    }

    public static Parser2<LexicalToken, Integer> count(Parser<LexicalToken> scanner)
    {
        return Parsers.<LexicalToken>count(scanner);
    }

    public static Parser<LexicalToken> fails(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>fails(parser);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static <TOutput> Parser2<LexicalToken, TOutput> first(Parser2<LexicalToken, TOutput>... parsers)
    {
        return Parsers.<LexicalToken, TOutput>first(parsers);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static Parser<LexicalToken> first(Parser<LexicalToken>... parsers)
    {
        return Parsers.<LexicalToken>first(parsers);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static <TOutput> RightParser<LexicalToken, TOutput> first(RightParser<LexicalToken, TOutput>... parsers)
    {
        return Parsers.<LexicalToken, TOutput>first(parsers);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> forward(Supplier<Parser2<LexicalToken, TOutput>> deferredParser)
    {
        return Parsers.<LexicalToken, TOutput>forward(deferredParser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> forward(Parser2<LexicalToken, TOutput> parser)
    {
        return Parsers.<LexicalToken, TOutput>forward(parser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> if_(Parser<LexicalToken> test, Parser2<LexicalToken, TOutput> parser)
    {
        return Parsers.<LexicalToken, TOutput>if_(test, parser);
    }

    public static <TOutput> RightParser<LexicalToken, TOutput> if_(Parser<LexicalToken> test, RightParser<LexicalToken, TOutput> parser)
    {
        return Parsers.<LexicalToken, TOutput>if_(test, parser);
    }

    public static Parser<LexicalToken> if_(Parser<LexicalToken> test, Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>if_(test, parser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> limit(Parser<LexicalToken> limiter, Parser2<LexicalToken, TOutput> limited)
    {
        return Parsers.<LexicalToken, TOutput>limit(limiter, limited);
    }

    public static <TElement, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, boolean oneOrMore, Function<List<TElement>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TProducer>list(elementParser, oneOrMore, producer);
    }

    public static <TElement, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingElement, boolean oneOrMore, Function<List<TElement>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TProducer>list(elementParser, fnMissingElement, oneOrMore, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> oList(Parser2<LexicalToken, TElement> elementParser, Parser2<LexicalToken, TSeparator> separatorParser, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingElement, BiFunction<Source<LexicalToken>, Integer, TSeparator> fnMissingSeparator, Parser<LexicalToken> endOfList, boolean oneOrMore, boolean allowTrailingSeparator, Function<List<Object>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>oList(elementParser, separatorParser, fnMissingElement, fnMissingSeparator, endOfList, oneOrMore, allowTrailingSeparator, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> oList(Parser2<LexicalToken, TElement> primaryElementParser, Parser2<LexicalToken, TSeparator> separatorParser, Parser2<LexicalToken, TElement> secondaryElementParser, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingPrimaryElement, BiFunction<Source<LexicalToken>, Integer, TSeparator> fnMissingSeparator, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingSecondaryElement, Parser<LexicalToken> endOfList, boolean oneOrMore, boolean allowTrailingSeparator, Function<List<Object>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>oList(primaryElementParser, separatorParser, secondaryElementParser, fnMissingPrimaryElement, fnMissingSeparator, fnMissingSecondaryElement, endOfList, oneOrMore, allowTrailingSeparator, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, Parser2<LexicalToken, TSeparator> separatorParser, Parser2<LexicalToken, TElement> secondaryElementParser, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingElement, BiFunction<Source<LexicalToken>, Integer, TSeparator> fnMissingSeparator, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingSecondaryElement, Parser<LexicalToken> endOfList, boolean oneOrMore, boolean allowTrailingSeparator, Function<List<ElementAndSeparator<TElement, TSeparator>>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>list(elementParser, separatorParser, secondaryElementParser, fnMissingElement, fnMissingSeparator, fnMissingSecondaryElement, endOfList, oneOrMore, allowTrailingSeparator, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, Parser2<LexicalToken, TSeparator> separatorParser, BiFunction<Source<LexicalToken>, Integer, TElement> fnMissingElement, BiFunction<Source<LexicalToken>, Integer, TSeparator> fnMissingSeparator, Parser<LexicalToken> endOfList, boolean oneOrMore, boolean allowTrailingSeparator, Function<List<ElementAndSeparator<TElement, TSeparator>>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>list(elementParser, separatorParser, fnMissingElement, fnMissingSeparator, endOfList, oneOrMore, allowTrailingSeparator, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, Parser2<LexicalToken, TSeparator> separatorParser, Parser2<LexicalToken, TElement> secondaryElementParser, boolean oneOrMore, Function<List<ElementAndSeparator<TElement, TSeparator>>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>list(elementParser, separatorParser, secondaryElementParser, oneOrMore, producer);
    }

    public static <TElement, TSeparator, TProducer> Parser2<LexicalToken, TProducer> list(Parser2<LexicalToken, TElement> elementParser, Parser2<LexicalToken, TSeparator> separatorParser, boolean oneOrMore, Function<List<ElementAndSeparator<TElement, TSeparator>>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TElement, TSeparator, TProducer>list(elementParser, separatorParser, oneOrMore, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> map(Iterable<Map.Entry<Iterable<LexicalToken>, TOutput>> keyValuePairs)
    {
        return Parsers.<LexicalToken, TOutput>map(keyValuePairs);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> mapList(Iterable<Map.Entry<Iterable<LexicalToken>, Supplier<TOutput>>> keyValuePairs)
    {
        return Parsers.<LexicalToken, TOutput>mapList(keyValuePairs);
    }

    public static Parser<LexicalToken> match(Predicate<LexicalToken> predicate)
    {
        return Parsers.<LexicalToken>match(predicate);
    }

    public static Parser<LexicalToken> match(SourceConsumer<LexicalToken> consumer)
    {
        return Parsers.<LexicalToken>match(consumer);
    }

    public static Parser<LexicalToken> match(LexicalToken item)
    {
        return Parsers.<LexicalToken>match(item);
    }

    public static Parser<LexicalToken> match(LexicalToken item, EqualityComparer<LexicalToken> comparer)
    {
        return Parsers.<LexicalToken>match(item, comparer);
    }

    public static Parser<LexicalToken> matchAny(List<LexicalToken> items)
    {
        return Parsers.<LexicalToken>matchAny(items);
    }

    public static Parser<LexicalToken> matchAny(LexicalToken... items)
    {
        return Parsers.<LexicalToken>matchAny(items);
    }

    public static Parser<LexicalToken> matchAny(List<LexicalToken> items, EqualityComparer<LexicalToken> comparer)
    {
        return Parsers.<LexicalToken>matchAny(items, comparer);
    }

    public static Parser<LexicalToken> matchSequence(List<LexicalToken> items)
    {
        return Parsers.<LexicalToken>matchSequence(items);
    }

    public static Parser<LexicalToken> matchSequence(List<LexicalToken> items, EqualityComparer<LexicalToken> comparer)
    {
        return Parsers.<LexicalToken>matchSequence(items, comparer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> match(Predicate<LexicalToken> predicate, Function<LexicalToken, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>match(predicate, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> match(SourceConsumer<LexicalToken> consumer, SourceProducer<LexicalToken, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>match(consumer, producer);
    }

    public static Parser<LexicalToken> not(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>not(parser);
    }

    public static <TParser, TProducer> Parser2<LexicalToken, TProducer> oneOrMore(Parser2<LexicalToken, TParser> parser, Function<List<TParser>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TParser, TProducer>oneOrMore(parser, producer);
    }

    public static <TParser> Parser2<LexicalToken, List<TParser>> oneOrMoreList(Parser2<LexicalToken, TParser> parser)
    {
        return Parsers.<LexicalToken, TParser>oneOrMoreList(parser);
    }

    public static Parser<LexicalToken> oneOrMore(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>oneOrMore(parser);
    }

    public static Parser<LexicalToken> optional(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>optional(parser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> optional(Parser2<LexicalToken, TOutput> parser)
    {
        return Parsers.<LexicalToken, TOutput>optional(parser);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> optional(Parser2<LexicalToken, TOutput> parser, Supplier<TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>optional(parser, producer);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static Parser<LexicalToken> or(Parser<LexicalToken>... parsers)
    {
        return Parsers.<LexicalToken>or(parsers);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> produce(Parser<LexicalToken> parser, Function<List<Object>, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>produce(parser, producer);
    }

    public static <TElement, TOutput> Parser2<LexicalToken, TOutput> produceList(Parser<LexicalToken> parser, Function<List<TElement>, TOutput> producer)
    {
        return Parsers.<LexicalToken, TElement, TOutput>produceList(parser, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> required(Parser2<LexicalToken, TOutput> parser, Supplier<TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>required(parser, producer);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> required(Parser2<LexicalToken, TOutput> parser, BiFunction<Source<LexicalToken>, Integer, TOutput> producer)
    {
        return Parsers.<LexicalToken, TOutput>required(parser, producer);
    }

    public static <TParser1, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Function<TParser1, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TOutput>rule(parser1, producer);
    }

    public static <TParser1, TParser2, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, BiFunction<TParser1, TParser2, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TOutput>rule(parser1, parser2, producer);
    }

    public static <TParser1, TParser2, TParser3, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Func3<TParser1, TParser2, TParser3, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TOutput>rule(parser1, parser2, parser3, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Func4<TParser1, TParser2, TParser3, TParser4, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TOutput>rule(parser1, parser2, parser3, parser4, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TParser5, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Parser2<LexicalToken, TParser5> parser5, Func5<TParser1, TParser2, TParser3, TParser4, TParser5, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TParser5, TOutput>rule(parser1, parser2, parser3, parser4, parser5, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Parser2<LexicalToken, TParser5> parser5, Parser2<LexicalToken, TParser6> parser6, Func6<TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TOutput>rule(parser1, parser2, parser3, parser4, parser5, parser6, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Parser2<LexicalToken, TParser5> parser5, Parser2<LexicalToken, TParser6> parser6, Parser2<LexicalToken, TParser7> parser7, Func7<TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TOutput>rule(parser1, parser2, parser3, parser4, parser5, parser6, parser7, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Parser2<LexicalToken, TParser5> parser5, Parser2<LexicalToken, TParser6> parser6, Parser2<LexicalToken, TParser7> parser7, Parser2<LexicalToken, TParser8> parser8, Func8<TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TOutput>rule(parser1, parser2, parser3, parser4, parser5, parser6, parser7, parser8, producer);
    }

    public static <TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TParser9, TOutput> Parser2<LexicalToken, TOutput> rule(Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser3> parser3, Parser2<LexicalToken, TParser4> parser4, Parser2<LexicalToken, TParser5> parser5, Parser2<LexicalToken, TParser6> parser6, Parser2<LexicalToken, TParser7> parser7, Parser2<LexicalToken, TParser8> parser8, Parser2<LexicalToken, TParser9> parser9, Func9<TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TParser9, TOutput> producer)
    {
        return Parsers.<LexicalToken, TParser1, TParser2, TParser3, TParser4, TParser5, TParser6, TParser7, TParser8, TParser9, TOutput>rule(parser1, parser2, parser3, parser4, parser5, parser6, parser7, parser8, parser9, producer);
    }

    public static <TLeft, TOutput> RightParser<LexicalToken, TOutput> rule(Parsers.LeftValue<TLeft> left, Function<TLeft, TOutput> producer)
    {
        return Parsers.<LexicalToken, TLeft, TOutput>rule(left, producer);
    }

    public static <TLeft, TParser1, TOutput> RightParser<LexicalToken, TOutput> rule(Parsers.LeftValue<TLeft> left, Parser2<LexicalToken, TParser1> parser1, BiFunction<TLeft, TParser1, TOutput> producer)
    {
        return Parsers.<LexicalToken, TLeft, TParser1, TOutput>rule(left, parser1, producer);
    }

    public static <TLeft, TParser1, TParser2, TOutput> RightParser<LexicalToken, TOutput> rule(Parsers.LeftValue<TLeft> left, Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Func3<TLeft, TParser1, TParser2, TOutput> producer)
    {
        return Parsers.<LexicalToken, TLeft, TParser1, TParser2, TOutput>rule(left, parser1, parser2, producer);
    }

    public static <TLeft, TParser1, TParser2, TParser3, TOutput> RightParser<LexicalToken, TOutput> rule(Parsers.LeftValue<TLeft> left, Parser2<LexicalToken, TParser1> parser1, Parser2<LexicalToken, TParser2> parser2, Parser2<LexicalToken, TParser2> parser3, Func4<TLeft, TParser1, TParser2, TParser3, TOutput> producer)
    {
        return Parsers.<LexicalToken, TLeft, TParser1, TParser2, TParser3, TOutput>rule(left, parser1, parser2, parser3, producer);
    }

    @SafeVarargs
    @SuppressWarnings("varargs")
    public static Parser<LexicalToken> sequence(Parser<LexicalToken>... parsers)
    {
        return Parsers.<LexicalToken>sequence(parsers);
    }

    public static Parser<LexicalToken> sequence(List<? extends Parser<LexicalToken>> parsers)
    {
        return Parsers.<LexicalToken>sequence(parsers);
    }

    public static <TOutput> Parser2<LexicalToken, TOutput> value(Supplier<TOutput> fnValue)
    {
        return Parsers.<LexicalToken, TOutput>value(fnValue);
    }

    public static <TParser, TProducer> Parser2<LexicalToken, TProducer> zeroOrMore(Parser2<LexicalToken, TParser> parser, Function<List<TParser>, TProducer> producer)
    {
        return Parsers.<LexicalToken, TParser, TProducer>zeroOrMore(parser, producer);
    }

    public static Parser<LexicalToken> zeroOrMore(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>zeroOrMore(parser);
    }

    public static <TParser> Parser2<LexicalToken, List<TParser>> zeroOrMoreList(Parser2<LexicalToken, TParser> parser)
    {
        return Parsers.<LexicalToken, TParser>zeroOrMoreList(parser);
    }

    public static Parser<LexicalToken> zeroOrOne(Parser<LexicalToken> parser)
    {
        return Parsers.<LexicalToken>zeroOrOne(parser);
    }
}
