// Ported from: src/Kusto.Language.Generators/CodeGenerator.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Upstream license: Apache-2.0, Copyright (c) 2019 Microsoft Corporation.
// This file is a derived work; see NOTICE. Modifications are marked "// PORT:".
package org.graylog.kusto.language.generator;

import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * A utility class for writing the text of other programs.
 *
 * <p>This class does not take a dependency on anything not in the BCL.
 */
class CodeGenerator { // PORT: §2.6 internal; package-private (the generator module cannot see @Internal)
    // region Private data
    private StringWriter m_swriter;
    private IndentedTextWriter m_writer;
    private boolean m_emptyAbove;
    // endregion

    // region Construction
    public CodeGenerator() {
        m_swriter = new StringWriter();
        m_writer = new IndentedTextWriter(m_swriter, "    ");
        m_emptyAbove = true;
    }
    // endregion

    // region Public API
    /**
     * Gets the full program text written thus far.
     */
    public String getText() {
        return m_swriter.toString();
    }

    public void writeHeader(String templateExtension, String templateName) {
        // PORT: §4 C# verbatim string literal as concatenation; the trailing blank after "429" is upstream's.
        writeLine("\n"
                + "// ----------------------------------------------------------------------------\n"
                + "// Copyright (c) Microsoft Corporation. All rights reserved.\n"
                + "// ----------------------------------------------------------------------------\n"
                + "// <autogenerated>\n"
                + "//   This file was generated automatically from a {0} file that included\n"
                + "//   the {1} file.\n"
                + "//   Do not modify this file by hand -- modify the original {0} file.\n"
                + "//   Do not check-in this file!\n"
                + "// </autogenerated>\n"
                + "\n"
                + "// Disable pragma warnings for auto-generated code\n"
                + "#pragma warning disable 472,429 \n", templateExtension, templateName);
    }

    // PORT: §4 Java-flavoured equivalent of WriteHeader: the PORTING.md 2.1/4.3 header of a generated file.
    public void writeJavaHeader(List<String> portedFrom, String upstreamCommit) {
        for (String source : portedFrom) {
            writeLine("// Ported from: " + source);
        }
        writeLine("// Upstream: microsoft/Kusto-Query-Language @ " + upstreamCommit);
        writeLine("// SPDX-License-Identifier: Apache-2.0");
        writeLine("// Copyright (c) Microsoft Corporation. All rights reserved.");
        writeLine("// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; "
                + "do not edit outside <hand-written> regions.");
    }

    /**
     * Add a block of "using namespace X".
     *
     * @param usingNamespaces The custom namespaces to "use" in the block.
     * @param addBclNamespaces Whether to add a few useful BCL namespace.
     * @param addKcpNamespaces Whether to add a few useful Kusto.Cloud.Platform namespaces.
     */
    public void writeUsingBlock(Iterable<String> usingNamespaces, boolean addBclNamespaces, boolean addKcpNamespaces) {
        var bclCommonNamespaces = new String[]
        {
            "System",
            "System.Collections.Generic",
            "System.Globalization",
            "System.Runtime.Serialization",
        };

        var kcpNamespaces = new ArrayList<String>(List.of(
            "Kusto.Cloud.Platform.Utils"
        ));

        var nsCommon = new ArrayList<String>();
        var nsDotNetOnly = new ArrayList<String>();

        if (addBclNamespaces) {
            for (var namspace : bclCommonNamespaces) {
                if (!nsCommon.contains(namspace)) {
                    nsCommon.add(namspace);
                }
            }

        }
        if (addKcpNamespaces) {
            for (var namspace : kcpNamespaces) {
                if (!nsCommon.contains(namspace)) {
                    nsCommon.add(namspace);
                }
            }
        }
        if (usingNamespaces != null) {
            for (var namspace : usingNamespaces) {
                if (!nsCommon.contains(namspace)) {
                    nsCommon.add(namspace);
                }
            }
        }

        for (String n : nsCommon) {
            writeLine("using {0};", n);
        }
    }

    // PORT: §4 Java-flavoured equivalent of WriteUsingBlock: java.* imports, a blank line, then the rest.
    public void writeImportBlock(List<String> imports) {
        if (imports.isEmpty()) {
            return;
        }
        writeEmptyLineIfNeeded();
        boolean java = false;
        for (String i : imports) {
            if (i.startsWith("java.")) {
                writeLine("import " + i + ";");
                java = true;
            }
        }
        boolean separated = !java;
        for (String i : imports) {
            if (!i.startsWith("java.")) {
                if (!separated) {
                    writeLine();
                    separated = true;
                }
                writeLine("import " + i + ";");
            }
        }
    }

    /**
     * Writes a namespace declaration and inside it runs a continuation action.
     * The namespace declaration is closed automatically once the action returns.
     *
     * @param namespace The namespace to create.
     * @param inside The action to run inside the namespace.
     */
    public void writeNamespaceDeclaration(String namespace, Runnable inside) {
        writeNamespaceDeclarationBegin(namespace);
        inside.run();
        writeNamespaceDeclarationEnd();
    }

    /**
     * Writes the beginning part of a namespace declaration.
     */
    public void writeNamespaceDeclarationBegin(String namespace) {
        writeLine();
        writeLine("namespace {0}", namespace);
        writeLine("{");
        m_writer.setIndent(m_writer.indent() + 1);
    }

    /**
     * Writes the ending part of a namespace declaration.
     */
    public void writeNamespaceDeclarationEnd() {
        m_writer.setIndent(m_writer.indent() - 1);
        writeLine("}");
    }

    // PORT: §4 Java-flavoured equivalent of WriteNamespaceDeclaration: a package clause has no block.
    public void writePackageDeclaration(String packageName) {
        writeLine("package " + packageName + ";");
    }

    /**
     * Writes an "if(@if) { inside(); }" block
     */
    public void writeIfBlock(String if_, Runnable inside) {
        writeScopeStart("if (" + if_ + ")");
        inside.run();
        writeScopeEnd();
    }

    /**
     * Writes an "if(@if) { body }" block
     */
    public void writeIfBlock(String if_, String body) {
        writeScopeStart("if (" + if_ + ")");
        writeLine(body);
        writeScopeEnd();
    }

    public void writeRegion(String region, Runnable inside) {
        writeRegionBegin(region);
        inside.run();
        writeRegionEnd(region);
    }

    public void writeRegionBegin(String region) {
        writeEmptyLineIfNeeded();
        writeLine("#region {0}", region);
        m_emptyAbove = true;
    }

    public void writeRegionEnd(String region) {
        writeLine("#endregion /* {0} */", region);
    }

    // PORT: §4 Java-flavoured equivalent of WriteRegion: a protected <hand-written> region (PORTING.md 4.4).
    // The content lines are written verbatim, without the writer's indentation.
    public void writeHandWrittenRegion(String from, List<String> content) {
        writeLine("// <hand-written from=\"" + from + "\">");
        for (String line : content) {
            m_writer.writeLineNoTabs(line);
        }
        writeLine("// </hand-written>");
    }

    // PORT: §4 the imports half of a hand-written partial (imports cannot live inside the class body).
    public void writeHandWrittenImports(List<String> content) {
        writeLine("// <hand-written-imports>");
        for (String line : content) {
            m_writer.writeLineNoTabs(line);
        }
        writeLine("// </hand-written-imports>");
    }

    public void writeDocString(String summary, String remarks) {
        if (!isNullOrWhiteSpace(summary)) {
            writeLine("/// <summary>");
            writeLine("/// {0}", summary);
            writeLine("/// </summary>");
        }

        if (!isNullOrEmpty(remarks)) {
            writeLine("/// <remarks>");
            writeLine("/// {0}", remarks);
            writeLine("/// </remarks>");
        }
    }

    public void writeDocString(String summary) { // PORT: §3.12 optional parameter remarks = null
        writeDocString(summary, null);
    }

    // PORT: §4 Java-flavoured equivalent of WriteDocString: Javadoc, same emptiness rules.
    public void writeJavaDocString(String summary, String remarks) {
        boolean hasSummary = !isNullOrWhiteSpace(summary);
        boolean hasRemarks = !isNullOrEmpty(remarks);
        if (!hasSummary && !hasRemarks) {
            return;
        }
        writeLine("/**");
        if (hasSummary) {
            writeLine(" * " + escapeJavadoc(summary), false);
        }
        if (hasRemarks) {
            if (hasSummary) {
                writeLine(" *", false);
            }
            writeLine(" * <p>" + escapeJavadoc(remarks), false);
        }
        writeLine(" */");
    }

    // PORT: §4 one-line Javadoc for members (property accessors, constructors).
    public void writeJavaDocLine(String summary) {
        if (!isNullOrWhiteSpace(summary)) {
            writeLine("/** " + escapeJavadoc(summary) + " */", false);
        }
    }

    /**
     * Writes a string and a new indented scope, calls the action,
     * then ends the scope.
     *
     * @param head The string preceding the new scope.
     * @param inside The action to run inside the scope.
     */
    public void writeScope(String head, Runnable inside) {
        writeScopeStart(head);
        inside.run();
        writeScopeEnd();
    }

    public void writeScopeStart() {
        writeLine("{");
        m_writer.setIndent(m_writer.indent() + 1);
    }

    public void writeScopeStart(String head) {
        writeLine(head);
        writeLine("{");
        m_writer.setIndent(m_writer.indent() + 1);
    }

    public void writeScopeEnd() {
        m_writer.setIndent(m_writer.indent() - 1);
        writeLine("}");
    }

    // PORT: §4 Java-flavoured equivalent of WriteScope: the opening brace ends the head line (PORTING.md 4.3).
    public void writeJavaScope(String head, Runnable inside) {
        writeJavaScopeStart(head);
        inside.run();
        writeScopeEnd();
    }

    // PORT: §4 Java-flavoured equivalent of WriteScopeStart(head).
    public void writeJavaScopeStart(String head) {
        writeLine(head + " {");
        m_writer.setIndent(m_writer.indent() + 1);
    }

    public void unsafeIndent() {
        m_writer.setIndent(m_writer.indent() + 1);
    }

    public void unsafeUnindent() {
        m_writer.setIndent(m_writer.indent() - 1);
    }

    /**
     * If the line above the current line is not empty, write a new line.
     */
    public void writeEmptyLineIfNeeded() {
        if (!m_emptyAbove) {
            writeLine((String) null);
        }
    }

    public void writeLine() {
        writeLine((String) null);
    }

    // PORT: §4 System.Environment.NewLine is always "\n" so the output is identical on every platform.
    private static final String[] c_newline = new String[] { "\n" };

    public void writeLine(String text, boolean detectNewLines) {
        if (isNullOrWhiteSpace(text)) {
            m_emptyAbove = true;
            m_writer.writeLineNoTabs(""); // PORT: §4 blank lines carry no indentation (upstream: m_writer.WriteLine())
            return;
        }

        if (detectNewLines && text.contains(c_newline[0])) {
            var lines = text.split(c_newline[0], -1); // PORT: §3.17 StringSplitOptions.None keeps empty entries
            for (var line : lines) {
                if (line.isEmpty()) {
                    m_writer.writeLineNoTabs(line); // PORT: §4 blank lines carry no indentation
                } else {
                    m_writer.writeLine(line);
                }
            }
        } else {
            m_writer.writeLine(text);
        }
        if (text.endsWith(c_newline[0]) || text.endsWith("{")) {
            m_emptyAbove = true;
        } else {
            m_emptyAbove = false;
        }
    }

    public void writeLine(String text) { // PORT: §3.12 optional parameter detectNewLines = true
        writeLine(text, true);
    }

    public void writeLine(String format, Object... args) {
        var text = format(format, args);
        writeLine(text);
    }
    // endregion

    // region Static utility methods
    /**
     * Given a compoundName/CompoundName, returns the corresponding PascalCase
     * version of the name (CompoundName).
     */
    public static String getPascalCase(String name) {
        if (isNullOrWhiteSpace(name)) {
            return name;
        }
        var first = Character.toUpperCase(name.charAt(0));
        if (name.length() == 1) {
            return String.valueOf(first);
        }
        return first + name.substring(1);
    }

    /**
     * Given a compoundName/CompoundName, returns the corresponding CamelCase
     * version of the name (compoundName).
     */
    public static String getCamelCase(String name) {
        if (isNullOrWhiteSpace(name)) {
            return name;
        }
        var first = Character.toLowerCase(name.charAt(0));
        if (name.length() == 1) {
            return String.valueOf(first);
        }
        var ret = first + name.substring(1);
        if (ret.equals("operator")) { // Add here all C# keywords people dream up
            return "@" + ret;
        }
        return ret;
    }

    // PORT: §4 Java-flavoured equivalent of GetCamelCase: escapes Java reserved words with a trailing
    // underscore (PORTING.md 2.3) instead of C# keywords with '@' ("operator" is a legal Java name).
    public static String getJavaCamelCase(String name) {
        if (isNullOrWhiteSpace(name)) {
            return name;
        }
        var ret = Character.toLowerCase(name.charAt(0)) + name.substring(1);
        return JAVA_RESERVED.contains(ret) ? ret + "_" : ret;
    }

    // PORT: §2.3 Java 21 reserved keywords and literals.
    private static final Set<String> JAVA_RESERVED = Set.of(
        "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
        "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float",
        "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native",
        "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp",
        "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void",
        "volatile", "while", "true", "false", "null", "_");

    /**
     * Given a compoundName/CompoundName, returns the corresponding ClassMemberName
     * version of the name(m_compoundName).
     */
    public static String getClassMemberName(String name) {
        return "m_" + getCamelCase(name);
    }

    // PORT: §4 string.IsNullOrWhiteSpace / string.IsNullOrEmpty
    static boolean isNullOrWhiteSpace(String s) {
        return s == null || s.isBlank();
    }

    static boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }

    // PORT: §4 string.Format composite formatting ({0}, {1}, "{{", "}}"); only what the generator uses.
    static String format(String format, Object... args) {
        var sb = new StringBuilder(format.length() + 16);
        int i = 0;
        int n = format.length();
        while (i < n) {
            char c = format.charAt(i);
            if (c == '{') {
                if (i + 1 < n && format.charAt(i + 1) == '{') {
                    sb.append('{');
                    i += 2;
                    continue;
                }
                int close = format.indexOf('}', i);
                if (close < 0) {
                    throw new IllegalArgumentException("Input string was not in a correct format."); // PORT: §3.16 FormatException
                }
                int index = Integer.parseInt(format.substring(i + 1, close).trim());
                if (index < 0 || index >= args.length) {
                    throw new IllegalArgumentException("Index (zero based) must be greater than or equal to zero and less than the size of the argument list."); // PORT: §3.16 FormatException
                }
                sb.append(args[index] == null ? "" : String.valueOf(args[index]));
                i = close + 1;
            } else if (c == '}') {
                if (i + 1 < n && format.charAt(i + 1) == '}') {
                    sb.append('}');
                    i += 2;
                    continue;
                }
                throw new IllegalArgumentException("Input string was not in a correct format."); // PORT: §3.16 FormatException
            } else {
                sb.append(c);
                i++;
            }
        }
        return sb.toString();
    }

    // PORT: §4 Javadoc must not contain HTML metacharacters, "*/", "@" tags or unicode escapes from data.
    static String escapeJavadoc(String text) {
        var sb = new StringBuilder(text.length());
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '&': sb.append("&amp;"); break;
                case '<': sb.append("&lt;"); break;
                case '>': sb.append("&gt;"); break;
                case '@': sb.append("&#64;"); break;
                case '\\': sb.append("&#92;"); break;
                case '/':
                    sb.append(i > 0 && text.charAt(i - 1) == '*' ? "&#47;" : "/");
                    break;
                default: sb.append(c);
            }
        }
        return sb.toString();
    }
    // endregion
}
