// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node AssertSchemaOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class AssertSchemaOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.AssertSchemaOperator; }
    private final SyntaxToken assertSchemaKeyword;
    public SyntaxToken assertSchemaKeyword() { return assertSchemaKeyword; }
    private final RowSchema schema;
    public RowSchema schema() { return schema; }

    /** Constructs a new instance of {@link AssertSchemaOperator}. */
    public AssertSchemaOperator(SyntaxToken assertSchemaKeyword, RowSchema schema, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.assertSchemaKeyword = attach(assertSchemaKeyword);
        this.schema = attach(schema);
        this.init();
    }
    public AssertSchemaOperator(SyntaxToken assertSchemaKeyword, RowSchema schema) { this(assertSchemaKeyword, schema, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return assertSchemaKeyword; case 1: return schema; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "AssertSchemaKeyword"; case 1: return "Schema"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitAssertSchemaOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitAssertSchemaOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new AssertSchemaOperator(assertSchemaKeyword != null ? (SyntaxToken) assertSchemaKeyword.clone(includeDiagnostics) : null,
            schema != null ? (RowSchema) schema.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
