// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node BracketedExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class BracketedExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.BracketedExpression; }
    private final SyntaxToken openBracket;
    public SyntaxToken openBracket() { return openBracket; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken closeBracket;
    public SyntaxToken closeBracket() { return closeBracket; }

    /** Constructs a new instance of {@link BracketedExpression}. */
    public BracketedExpression(SyntaxToken openBracket, Expression expression, SyntaxToken closeBracket, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBracket = attach(openBracket);
        this.expression = attach(expression);
        this.closeBracket = attach(closeBracket);
        this.init();
    }
    public BracketedExpression(SyntaxToken openBracket, Expression expression, SyntaxToken closeBracket) { this(openBracket, expression, closeBracket, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBracket; case 1: return expression; case 2: return closeBracket; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBracket"; case 1: return "Expression"; case 2: return "CloseBracket"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Literal; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitBracketedExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitBracketedExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new BracketedExpression(openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
