// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node BracedName)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

// <hand-written-imports>
// </hand-written-imports>

/**
 * A node in the kusto syntax that represents a client parameter.
 */
public final class BracedName extends Name {
    @Override public SyntaxKind kind() { return SyntaxKind.BracedName; }
    private final SyntaxToken openBrace;
    public SyntaxToken openBrace() { return openBrace; }
    private final SyntaxToken name;
    public SyntaxToken name() { return name; }
    private final SyntaxToken closeBrace;
    public SyntaxToken closeBrace() { return closeBrace; }

    /** Constructs a new instance of {@link BracedName}. */
    public BracedName(SyntaxToken openBrace, SyntaxToken name, SyntaxToken closeBrace, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBrace = attach(openBrace);
        this.name = attach(name);
        this.closeBrace = attach(closeBrace);
        this.init();
    }
    public BracedName(SyntaxToken openBrace, SyntaxToken name, SyntaxToken closeBrace) { this(openBrace, name, closeBrace, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBrace; case 1: return name; case 2: return closeBrace; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBrace"; case 1: return "Name"; case 2: return "CloseBrace"; default: throw new IndexOutOfBoundsException(); } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitBracedName(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitBracedName(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new BracedName(openBrace != null ? (SyntaxToken) openBrace.clone(includeDiagnostics) : null,
            name != null ? (SyntaxToken) name.clone(includeDiagnostics) : null,
            closeBrace != null ? (SyntaxToken) closeBrace.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:232-235">
    @Override
    public String simpleName() { return this.name().valueText(); }
    // </hand-written>
}
