// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node BracketedWildcardedName)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

public final class BracketedWildcardedName extends Name {
    @Override public SyntaxKind kind() { return SyntaxKind.BracketedWildcardedName; }
    private final SyntaxToken openBracket;
    /** The open bracket token. */
    public SyntaxToken openBracket() { return openBracket; }
    private final SyntaxToken pattern;
    public SyntaxToken pattern() { return pattern; }
    private final SyntaxToken closeBracket;
    /** The close bracket token. */
    public SyntaxToken closeBracket() { return closeBracket; }

    /** Constructs a new instance of {@link BracketedWildcardedName}. */
    public BracketedWildcardedName(SyntaxToken openBracket, SyntaxToken pattern, SyntaxToken closeBracket, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBracket = attach(openBracket);
        this.pattern = attach(pattern);
        this.closeBracket = attach(closeBracket);
        this.init();
    }
    public BracketedWildcardedName(SyntaxToken openBracket, SyntaxToken pattern, SyntaxToken closeBracket) { this(openBracket, pattern, closeBracket, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBracket; case 1: return pattern; case 2: return closeBracket; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBracket"; case 1: return "Pattern"; case 2: return "CloseBracket"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitBracketedWildcardedName(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitBracketedWildcardedName(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new BracketedWildcardedName(openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            pattern != null ? (SyntaxToken) pattern.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:242-245">
    @Override
    public String simpleName() { return this.pattern().valueText(); }
    // </hand-written>
}
