// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node BracketedName)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

/**
 * A node in the kusto syntax that represents a bracketed name.
 */
public final class BracketedName extends Name {
    @Override public SyntaxKind kind() { return SyntaxKind.BracketedName; }
    private final SyntaxToken openBracket;
    /** The open bracket token. */
    public SyntaxToken openBracket() { return openBracket; }
    private final Expression name;
    /** The string literal expression that comprises the name. */
    public Expression name() { return name; }
    private final SyntaxToken closeBracket;
    /** The close bracket token. */
    public SyntaxToken closeBracket() { return closeBracket; }

    /** Constructs a new instance of {@link BracketedName}. */
    public BracketedName(SyntaxToken openBracket, Expression name, SyntaxToken closeBracket, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBracket = attach(openBracket);
        this.name = attach(name);
        this.closeBracket = attach(closeBracket);
        this.init();
    }
    public BracketedName(SyntaxToken openBracket, Expression name, SyntaxToken closeBracket) { this(openBracket, name, closeBracket, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBracket; case 1: return name; case 2: return closeBracket; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBracket"; case 1: return "Name"; case 2: return "CloseBracket"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Literal; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitBracketedName(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitBracketedName(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new BracketedName(openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            name != null ? (Expression) name.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:227-230">
    @Override
    public String simpleName() { return this.name().literalValue() instanceof String s ? s : ""; } // PORT: §3.15 'as string ??'
    // </hand-written>
}
