// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node CommandAndSkippedTokens)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class CommandAndSkippedTokens extends Command {
    @Override public SyntaxKind kind() { return SyntaxKind.CommandAndSkippedTokens; }
    private final Command command;
    public Command command() { return command; }
    private final SkippedTokens skippedTokens;
    public SkippedTokens skippedTokens() { return skippedTokens; }

    /** Constructs a new instance of {@link CommandAndSkippedTokens}. */
    public CommandAndSkippedTokens(Command command, SkippedTokens skippedTokens, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.command = attach(command);
        this.skippedTokens = attach(skippedTokens, true);
        this.init();
    }
    public CommandAndSkippedTokens(Command command, SkippedTokens skippedTokens) { this(command, skippedTokens, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return command; case 1: return skippedTokens; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Command"; case 1: return "SkippedTokens"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.NonScalar; case 1: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitCommandAndSkippedTokens(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitCommandAndSkippedTokens(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new CommandAndSkippedTokens(command != null ? (Command) command.clone(includeDiagnostics) : null,
            skippedTokens != null ? (SkippedTokens) skippedTokens.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
