// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ContextualDataTableExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ContextualDataTableExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.ContextualDataTableExpression; }
    private final SyntaxToken contextualDataTableKeyword;
    public SyntaxToken contextualDataTableKeyword() { return contextualDataTableKeyword; }
    private final Expression id;
    public Expression id() { return id; }
    private final RowSchema schema;
    public RowSchema schema() { return schema; }

    /** Constructs a new instance of {@link ContextualDataTableExpression}. */
    public ContextualDataTableExpression(SyntaxToken contextualDataTableKeyword, Expression id, RowSchema schema, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.contextualDataTableKeyword = attach(contextualDataTableKeyword);
        this.id = attach(id);
        this.schema = attach(schema);
        this.init();
    }
    public ContextualDataTableExpression(SyntaxToken contextualDataTableKeyword, Expression id, RowSchema schema) { this(contextualDataTableKeyword, id, schema, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return contextualDataTableKeyword; case 1: return id; case 2: return schema; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ContextualDataTableKeyword"; case 1: return "Id"; case 2: return "Schema"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitContextualDataTableExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitContextualDataTableExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ContextualDataTableExpression(contextualDataTableKeyword != null ? (SyntaxToken) contextualDataTableKeyword.clone(includeDiagnostics) : null,
            id != null ? (Expression) id.clone(includeDiagnostics) : null,
            schema != null ? (RowSchema) schema.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
