// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node CountAsIdentifierClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class CountAsIdentifierClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.CountAsIdentifierClause; }
    private final SyntaxToken asKeyword;
    public SyntaxToken asKeyword() { return asKeyword; }
    private final SyntaxToken identifier;
    public SyntaxToken identifier() { return identifier; }

    /** Constructs a new instance of {@link CountAsIdentifierClause}. */
    public CountAsIdentifierClause(SyntaxToken asKeyword, SyntaxToken identifier, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.asKeyword = attach(asKeyword);
        this.identifier = attach(identifier);
        this.init();
    }
    public CountAsIdentifierClause(SyntaxToken asKeyword, SyntaxToken identifier) { this(asKeyword, identifier, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return asKeyword; case 1: return identifier; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "AsKeyword"; case 1: return "Identifier"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Declaration; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitCountAsIdentifierClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitCountAsIdentifierClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new CountAsIdentifierClause(asKeyword != null ? (SyntaxToken) asKeyword.clone(includeDiagnostics) : null,
            identifier != null ? (SyntaxToken) identifier.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
