// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node DataScopeExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class DataScopeExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.DataScopeExpression; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final DataScopeClause dataScopeClause;
    public DataScopeClause dataScopeClause() { return dataScopeClause; }

    /** Constructs a new instance of {@link DataScopeExpression}. */
    public DataScopeExpression(Expression expression, DataScopeClause dataScopeClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.expression = attach(expression);
        this.dataScopeClause = attach(dataScopeClause);
        this.init();
    }
    public DataScopeExpression(Expression expression, DataScopeClause dataScopeClause) { this(expression, dataScopeClause, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return expression; case 1: return dataScopeClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Expression"; case 1: return "DataScopeClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitDataScopeExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitDataScopeExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new DataScopeExpression(expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            dataScopeClause != null ? (DataScopeClause) dataScopeClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
