// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node DataScopeClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class DataScopeClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.DataScopeClause; }
    private final SyntaxToken dataScopeKeyword;
    public SyntaxToken dataScopeKeyword() { return dataScopeKeyword; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final SyntaxToken value;
    public SyntaxToken value() { return value; }

    /** Constructs a new instance of {@link DataScopeClause}. */
    public DataScopeClause(SyntaxToken dataScopeKeyword, SyntaxToken equalToken, SyntaxToken value, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.dataScopeKeyword = attach(dataScopeKeyword);
        this.equalToken = attach(equalToken);
        this.value = attach(value);
        this.init();
    }
    public DataScopeClause(SyntaxToken dataScopeKeyword, SyntaxToken equalToken, SyntaxToken value) { this(dataScopeKeyword, equalToken, value, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return dataScopeKeyword; case 1: return equalToken; case 2: return value; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "DataScopeKeyword"; case 1: return "EqualToken"; case 2: return "Value"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Keyword; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitDataScopeClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitDataScopeClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new DataScopeClause(dataScopeKeyword != null ? (SyntaxToken) dataScopeKeyword.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            value != null ? (SyntaxToken) value.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
