// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (visitor DefaultSyntaxVisitor1)
// Ported from: src/Kusto.Language/Syntax/SyntaxVisitor.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

// <hand-written-imports>
// </hand-written-imports>

public abstract class DefaultSyntaxVisitor1<TResult> extends SyntaxVisitor1<TResult> {
    protected abstract TResult defaultVisit(SyntaxNode node);

    @Override public TResult visitDirectiveBlock(DirectiveBlock node) { return this.defaultVisit(node); }
    @Override public TResult visitDirective(Directive node) { return this.defaultVisit(node); }
    @Override public TResult visitSkippedTokens(SkippedTokens node) { return this.defaultVisit(node); }
    @Override public TResult visitQueryBlock(QueryBlock node) { return this.defaultVisit(node); }
    @Override public TResult visitTypeOfLiteralExpression(TypeOfLiteralExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitBadQueryOperator(BadQueryOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitCompoundStringLiteralExpression(CompoundStringLiteralExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitTokenName(TokenName node) { return this.defaultVisit(node); }
    @Override public TResult visitBracketedName(BracketedName node) { return this.defaultVisit(node); }
    @Override public TResult visitBracedName(BracedName node) { return this.defaultVisit(node); }
    @Override public TResult visitWildcardedName(WildcardedName node) { return this.defaultVisit(node); }
    @Override public TResult visitBracketedWildcardedName(BracketedWildcardedName node) { return this.defaultVisit(node); }
    @Override public TResult visitNameDeclaration(NameDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitNameReference(NameReference node) { return this.defaultVisit(node); }
    @Override public TResult visitLiteralExpression(LiteralExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitStarExpression(StarExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitAtExpression(AtExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitJsonPair(JsonPair node) { return this.defaultVisit(node); }
    @Override public TResult visitJsonObjectExpression(JsonObjectExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitJsonArrayExpression(JsonArrayExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitDynamicExpression(DynamicExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitParenthesizedExpression(ParenthesizedExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitExpressionList(ExpressionList node) { return this.defaultVisit(node); }
    @Override public TResult visitExpressionCouple(ExpressionCouple node) { return this.defaultVisit(node); }
    @Override public TResult visitPrefixUnaryExpression(PrefixUnaryExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitBinaryExpression(BinaryExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitInExpression(InExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitHasAnyExpression(HasAnyExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitHasAllExpression(HasAllExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitBetweenExpression(BetweenExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitFunctionCallExpression(FunctionCallExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitToScalarExpression(ToScalarExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitToTableExpression(ToTableExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitMaterializedViewCombineExpression(MaterializedViewCombineExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitMaterializedViewCombineNameClause(MaterializedViewCombineNameClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMaterializedViewCombineClause(MaterializedViewCombineClause node) { return this.defaultVisit(node); }
    @Override public TResult visitSimpleNamedExpression(SimpleNamedExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitRenameList(RenameList node) { return this.defaultVisit(node); }
    @Override public TResult visitCompoundNamedExpression(CompoundNamedExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitBracketedExpression(BracketedExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitPathExpression(PathExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitElementExpression(ElementExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitPipeExpression(PipeExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitRangeOperator(RangeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitNamedParameter(NamedParameter node) { return this.defaultVisit(node); }
    @Override public TResult visitConsumeOperator(ConsumeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitCountOperator(CountOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitCountAsIdentifierClause(CountAsIdentifierClause node) { return this.defaultVisit(node); }
    @Override public TResult visitExecuteAndCacheOperator(ExecuteAndCacheOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitExtendOperator(ExtendOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitFacetOperator(FacetOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitFacetWithOperatorClause(FacetWithOperatorClause node) { return this.defaultVisit(node); }
    @Override public TResult visitFacetWithExpressionClause(FacetWithExpressionClause node) { return this.defaultVisit(node); }
    @Override public TResult visitFilterOperator(FilterOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGetSchemaOperator(GetSchemaOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitFindOperator(FindOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitDataScopeClause(DataScopeClause node) { return this.defaultVisit(node); }
    @Override public TResult visitTypedColumnReference(TypedColumnReference node) { return this.defaultVisit(node); }
    @Override public TResult visitFindInClause(FindInClause node) { return this.defaultVisit(node); }
    @Override public TResult visitFindProjectClause(FindProjectClause node) { return this.defaultVisit(node); }
    @Override public TResult visitPackExpression(PackExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitNameAndTypeDeclaration(NameAndTypeDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitPrimitiveTypeExpression(PrimitiveTypeExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitSearchOperator(SearchOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitForkOperator(ForkOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitNameEqualsClause(NameEqualsClause node) { return this.defaultVisit(node); }
    @Override public TResult visitForkExpression(ForkExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesOperator(MakeSeriesOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesExpression(MakeSeriesExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitDefaultExpressionClause(DefaultExpressionClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesOnClause(MakeSeriesOnClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesFromClause(MakeSeriesFromClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesToClause(MakeSeriesToClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesStepClause(MakeSeriesStepClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesInRangeClause(MakeSeriesInRangeClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesFromToStepClause(MakeSeriesFromToStepClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeSeriesByClause(MakeSeriesByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMvExpandOperator(MvExpandOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMvExpandExpression(MvExpandExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitMvExpandRowLimitClause(MvExpandRowLimitClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMvApplyOperator(MvApplyOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMvApplyExpression(MvApplyExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitMvApplyRowLimitClause(MvApplyRowLimitClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMvApplyContextIdClause(MvApplyContextIdClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMvApplySubqueryExpression(MvApplySubqueryExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitToTypeOfClause(ToTypeOfClause node) { return this.defaultVisit(node); }
    @Override public TResult visitEvaluateSchemaClause(EvaluateSchemaClause node) { return this.defaultVisit(node); }
    @Override public TResult visitEvaluateOperator(EvaluateOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitParseOperator(ParseOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitParseWhereOperator(ParseWhereOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitParseKvWithClause(ParseKvWithClause node) { return this.defaultVisit(node); }
    @Override public TResult visitParseKvOperator(ParseKvOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionOperator(PartitionOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionQuery(PartitionQuery node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionScope(PartitionScope node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionSubquery(PartitionSubquery node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectOperator(ProjectOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectAwayOperator(ProjectAwayOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectByNamesOperator(ProjectByNamesOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectKeepOperator(ProjectKeepOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectRenameOperator(ProjectRenameOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectReorderOperator(ProjectReorderOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitSampleOperator(SampleOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitSampleDistinctOperator(SampleDistinctOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitEntityGroup(EntityGroup node) { return this.defaultVisit(node); }
    @Override public TResult visitReduceByOperator(ReduceByOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitReduceByWithClause(ReduceByWithClause node) { return this.defaultVisit(node); }
    @Override public TResult visitSummarizeOperator(SummarizeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMacroExpandScopeReferenceName(MacroExpandScopeReferenceName node) { return this.defaultVisit(node); }
    @Override public TResult visitMacroExpandOperator(MacroExpandOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitSummarizeByClause(SummarizeByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitDistinctOperator(DistinctOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitTakeOperator(TakeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitSortOperator(SortOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitOrderedExpression(OrderedExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitOrderingClause(OrderingClause node) { return this.defaultVisit(node); }
    @Override public TResult visitOrderingNullsClause(OrderingNullsClause node) { return this.defaultVisit(node); }
    @Override public TResult visitTopHittersOperator(TopHittersOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitTopHittersByClause(TopHittersByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitTopOperator(TopOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitTopNestedOperator(TopNestedOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitTopNestedClause(TopNestedClause node) { return this.defaultVisit(node); }
    @Override public TResult visitTopNestedWithOthersClause(TopNestedWithOthersClause node) { return this.defaultVisit(node); }
    @Override public TResult visitUnionOperator(UnionOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitAsOperator(AsOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitSerializeOperator(SerializeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitInvokeOperator(InvokeOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitRenderOperator(RenderOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeGraphOperator(MakeGraphOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeGraphWithTablesAndKeysClause(MakeGraphWithTablesAndKeysClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeGraphWithImplicitIdClause(MakeGraphWithImplicitIdClause node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMarkComponentsOperator(GraphMarkComponentsOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphWhereNodesOperator(GraphWhereNodesOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphWhereEdgesOperator(GraphWhereEdgesOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeGraphTableAndKeyClause(MakeGraphTableAndKeyClause node) { return this.defaultVisit(node); }
    @Override public TResult visitMakeGraphPartitionedByClause(MakeGraphPartitionedByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphToTableOperator(GraphToTableOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphToTableOutputClause(GraphToTableOutputClause node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphToTableAsClause(GraphToTableAsClause node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMatchOperator(GraphMatchOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphShortestPathsOperator(GraphShortestPathsOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMatchPattern(GraphMatchPattern node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMatchPatternNode(GraphMatchPatternNode node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMatchPatternEdge(GraphMatchPatternEdge node) { return this.defaultVisit(node); }
    @Override public TResult visitGraphMatchPatternEdgeRange(GraphMatchPatternEdgeRange node) { return this.defaultVisit(node); }
    @Override public TResult visitWhereClause(WhereClause node) { return this.defaultVisit(node); }
    @Override public TResult visitProjectClause(ProjectClause node) { return this.defaultVisit(node); }
    @Override public TResult visitNameReferenceList(NameReferenceList node) { return this.defaultVisit(node); }
    @Override public TResult visitRenderWithClause(RenderWithClause node) { return this.defaultVisit(node); }
    @Override public TResult visitPrintOperator(PrintOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitAliasStatement(AliasStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitLetStatement(LetStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitFunctionDeclaration(FunctionDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitFunctionParameters(FunctionParameters node) { return this.defaultVisit(node); }
    @Override public TResult visitFunctionParameter(FunctionParameter node) { return this.defaultVisit(node); }
    @Override public TResult visitDefaultValueDeclaration(DefaultValueDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitFunctionBody(FunctionBody node) { return this.defaultVisit(node); }
    @Override public TResult visitSchemaTypeExpression(SchemaTypeExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitExpressionStatement(ExpressionStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitMaterializeExpression(MaterializeExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitSetOptionStatement(SetOptionStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitOptionValueClause(OptionValueClause node) { return this.defaultVisit(node); }
    @Override public TResult visitQueryParametersStatement(QueryParametersStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitRestrictStatementWithClause(RestrictStatementWithClause node) { return this.defaultVisit(node); }
    @Override public TResult visitRestrictStatement(RestrictStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitPatternStatement(PatternStatement node) { return this.defaultVisit(node); }
    @Override public TResult visitPatternDeclaration(PatternDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitPatternPathParameter(PatternPathParameter node) { return this.defaultVisit(node); }
    @Override public TResult visitPatternMatch(PatternMatch node) { return this.defaultVisit(node); }
    @Override public TResult visitPatternPathValue(PatternPathValue node) { return this.defaultVisit(node); }
    @Override public TResult visitDataScopeExpression(DataScopeExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitDataTableExpression(DataTableExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitRowSchema(RowSchema node) { return this.defaultVisit(node); }
    @Override public TResult visitEvaluateRowSchema(EvaluateRowSchema node) { return this.defaultVisit(node); }
    @Override public TResult visitExternalDataExpression(ExternalDataExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitContextualDataTableExpression(ContextualDataTableExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitExternalDataWithClause(ExternalDataWithClause node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTableKindClause(InlineExternalTableKindClause node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTableDataFormatClause(InlineExternalTableDataFormatClause node) { return this.defaultVisit(node); }
    @Override public TResult visitDateTimePattern(DateTimePattern node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTablePathFormatPartitionColumnReference(InlineExternalTablePathFormatPartitionColumnReference node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTablePathFormatClause(InlineExternalTablePathFormatClause node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionColumnDeclaration(PartitionColumnDeclaration node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTablePartitionClause(InlineExternalTablePartitionClause node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTableConnectionStringsClause(InlineExternalTableConnectionStringsClause node) { return this.defaultVisit(node); }
    @Override public TResult visitInlineExternalTableExpression(InlineExternalTableExpression node) { return this.defaultVisit(node); }
    @Override public TResult visitJoinOperator(JoinOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitLookupOperator(LookupOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitJoinOnClause(JoinOnClause node) { return this.defaultVisit(node); }
    @Override public TResult visitJoinWhereClause(JoinWhereClause node) { return this.defaultVisit(node); }
    @Override public TResult visitScanOperator(ScanOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitAssertSchemaOperator(AssertSchemaOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitScanDeclareClause(ScanDeclareClause node) { return this.defaultVisit(node); }
    @Override public TResult visitScanOrderByClause(ScanOrderByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitScanPartitionByClause(ScanPartitionByClause node) { return this.defaultVisit(node); }
    @Override public TResult visitScanStepOutput(ScanStepOutput node) { return this.defaultVisit(node); }
    @Override public TResult visitScanStep(ScanStep node) { return this.defaultVisit(node); }
    @Override public TResult visitScanComputationClause(ScanComputationClause node) { return this.defaultVisit(node); }
    @Override public TResult visitScanAssignment(ScanAssignment node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionByOperator(PartitionByOperator node) { return this.defaultVisit(node); }
    @Override public TResult visitPartitionByIdClause(PartitionByIdClause node) { return this.defaultVisit(node); }
    @Override public TResult visitCommandWithValueClause(CommandWithValueClause node) { return this.defaultVisit(node); }
    @Override public TResult visitCommandWithPropertyListClause(CommandWithPropertyListClause node) { return this.defaultVisit(node); }
    @Override public TResult visitUnknownCommand(UnknownCommand node) { return this.defaultVisit(node); }
    @Override public TResult visitCustomCommand(CustomCommand node) { return this.defaultVisit(node); }
    @Override public TResult visitPartialCommand(PartialCommand node) { return this.defaultVisit(node); }
    @Override public TResult visitCommandAndSkippedTokens(CommandAndSkippedTokens node) { return this.defaultVisit(node); }
    @Override public TResult visitBadCommand(BadCommand node) { return this.defaultVisit(node); }
    @Override public TResult visitCommandBlock(CommandBlock node) { return this.defaultVisit(node); }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxVisitor.cs:46-62">
    @Override
    public TResult visitCustom(CustomNode node)
    {
        return this.defaultVisit(node);
    }

    @Override
    public TResult visitList(SyntaxList list)
    {
        return this.defaultVisit(list);
    }

    @Override
    public TResult visitSeparatedElement(SeparatedElement separatedElement)
    {
        return this.defaultVisit(separatedElement);
    }
    // </hand-written>
}
