// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node DefaultValueDeclaration)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class DefaultValueDeclaration extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.DefaultValueDeclaration; }
    private final SyntaxToken equal;
    public SyntaxToken equal() { return equal; }
    private final Expression value;
    public Expression value() { return value; }

    /** Constructs a new instance of {@link DefaultValueDeclaration}. */
    public DefaultValueDeclaration(SyntaxToken equal, Expression value, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.equal = attach(equal);
        this.value = attach(value);
        this.init();
    }
    public DefaultValueDeclaration(SyntaxToken equal, Expression value) { this(equal, value, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return equal; case 1: return value; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Equal"; case 1: return "Value"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitDefaultValueDeclaration(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitDefaultValueDeclaration(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new DefaultValueDeclaration(equal != null ? (SyntaxToken) equal.clone(includeDiagnostics) : null,
            value != null ? (Expression) value.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
