// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node Directive)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
import java.lang.invoke.VarHandle;
import java.util.List;
import org.graylog.kusto.language.editor.ClientDirective;
import org.graylog.kusto.language.editor.ClientDirectiveArgument;
import org.graylog.kusto.language.editor.EditString;
import org.graylog.kusto.language.utils.Interlocked;
import org.graylog.kusto.language.utils.dotnet.Out;
// </hand-written-imports>

public final class Directive extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.Directive; }
    private final SyntaxToken token;
    public SyntaxToken token() { return token; }

    /** Constructs a new instance of {@link Directive}. */
    public Directive(SyntaxToken token, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.token = attach(token);
        this.init();
    }
    public Directive(SyntaxToken token) { this(token, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return token; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Token"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitDirective(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitDirective(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new Directive(token != null ? (SyntaxToken) token.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:262-296">
    /// <summary>
    /// The name of the directive
    /// </summary>
    public String name() { return this.info().name(); }

    /// <summary>
    /// The text after the name contain any arguments
    /// </summary>
    public String argumentsText() { return this.info().argumentsText().toString(); } // PORT: §3.8 implicit EditString → string

    /// <summary>
    /// The text parsed into arguments.
    /// </summary>
    public List<ClientDirectiveArgument> arguments() { return this.info().arguments(); }

    /// <summary>
    /// The parsed client directive.
    /// </summary>
    private ClientDirective info()
    {
        if (_lazyClientDirective == null)
        {
            var info = new Out<ClientDirective>(); // PORT: §3.3
            ClientDirective.tryParse(EditString.of(this.token().text()), info); // PORT: §3.8 implicit string → EditString
            Interlocked.compareExchange(LAZY_CLIENT_DIRECTIVE, this, info.value, null); // PORT: §3.13
        }
        return _lazyClientDirective;
    }

    private volatile ClientDirective _lazyClientDirective; // PORT: §3.13 CAS-published
    private static final VarHandle LAZY_CLIENT_DIRECTIVE = Interlocked.handle(Directive.class, "_lazyClientDirective", ClientDirective.class); // PORT: §3.13
    // </hand-written>
}
