// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ElementExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ElementExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.ElementExpression; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final Expression selector;
    public Expression selector() { return selector; }

    /** Constructs a new instance of {@link ElementExpression}. */
    public ElementExpression(Expression expression, Expression selector, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.expression = attach(expression);
        this.selector = attach(selector);
        this.init();
    }
    public ElementExpression(Expression expression, Expression selector) { this(expression, selector, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return expression; case 1: return selector; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Expression"; case 1: return "Selector"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitElementExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitElementExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ElementExpression(expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            selector != null ? (Expression) selector.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
