// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node EvaluateRowSchema)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class EvaluateRowSchema extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.EvaluateRowSchema; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxToken leadingComma;
    public SyntaxToken leadingComma() { return leadingComma; }
    private final SyntaxToken asteriskToken;
    public SyntaxToken asteriskToken() { return asteriskToken; }
    private final SyntaxToken asteriskTokenComma;
    public SyntaxToken asteriskTokenComma() { return asteriskTokenComma; }
    private final SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> columns;
    public SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> columns() { return columns; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link EvaluateRowSchema}. */
    public EvaluateRowSchema(SyntaxToken openParen, SyntaxToken leadingComma, SyntaxToken asteriskToken, SyntaxToken asteriskTokenComma, SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> columns, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openParen = attach(openParen);
        this.leadingComma = attach(leadingComma, true);
        this.asteriskToken = attach(asteriskToken, true);
        this.asteriskTokenComma = attach(asteriskTokenComma, true);
        this.columns = attach(columns);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public EvaluateRowSchema(SyntaxToken openParen, SyntaxToken leadingComma, SyntaxToken asteriskToken, SyntaxToken asteriskTokenComma, SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> columns, SyntaxToken closeParen) { this(openParen, leadingComma, asteriskToken, asteriskTokenComma, columns, closeParen, null); }

    @Override public int childCount() { return 6; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openParen; case 1: return leadingComma; case 2: return asteriskToken; case 3: return asteriskTokenComma; case 4: return columns; case 5: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenParen"; case 1: return "LeadingComma"; case 2: return "AsteriskToken"; case 3: return "AsteriskTokenComma"; case 4: return "Columns"; case 5: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: case 2: case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Declaration; case 5: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitEvaluateRowSchema(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitEvaluateRowSchema(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new EvaluateRowSchema(openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            leadingComma != null ? (SyntaxToken) leadingComma.clone(includeDiagnostics) : null,
            asteriskToken != null ? (SyntaxToken) asteriskToken.clone(includeDiagnostics) : null,
            asteriskTokenComma != null ? (SyntaxToken) asteriskTokenComma.clone(includeDiagnostics) : null,
            columns != null ? (SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>>) columns.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
