// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node EvaluateSchemaClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class EvaluateSchemaClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.EvaluateSchemaClause; }
    private final SyntaxToken colonToken;
    public SyntaxToken colonToken() { return colonToken; }
    private final EvaluateRowSchema schema;
    public EvaluateRowSchema schema() { return schema; }

    /** Constructs a new instance of {@link EvaluateSchemaClause}. */
    public EvaluateSchemaClause(SyntaxToken colonToken, EvaluateRowSchema schema, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.colonToken = attach(colonToken);
        this.schema = attach(schema, true);
        this.init();
    }
    public EvaluateSchemaClause(SyntaxToken colonToken, EvaluateRowSchema schema) { this(colonToken, schema, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return colonToken; case 1: return schema; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ColonToken"; case 1: return "Schema"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitEvaluateSchemaClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitEvaluateSchemaClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new EvaluateSchemaClause(colonToken != null ? (SyntaxToken) colonToken.clone(includeDiagnostics) : null,
            schema != null ? (EvaluateRowSchema) schema.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
