// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ExecuteAndCacheOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

public final class ExecuteAndCacheOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ExecuteAndCacheOperator; }
    private final SyntaxToken executeAndCacheKeyword;
    public SyntaxToken executeAndCacheKeyword() { return executeAndCacheKeyword; }

    /** Constructs a new instance of {@link ExecuteAndCacheOperator}. */
    public ExecuteAndCacheOperator(SyntaxToken executeAndCacheKeyword, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.executeAndCacheKeyword = attach(executeAndCacheKeyword);
        this.init();
    }
    public ExecuteAndCacheOperator(SyntaxToken executeAndCacheKeyword) { this(executeAndCacheKeyword, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return executeAndCacheKeyword; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ExecuteAndCacheKeyword"; default: throw new IndexOutOfBoundsException(); } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitExecuteAndCacheOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitExecuteAndCacheOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ExecuteAndCacheOperator(executeAndCacheKeyword != null ? (SyntaxToken) executeAndCacheKeyword.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
