// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node Expression)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Ported from: src/Kusto.Language/Syntax/SyntaxNode_Semantics.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

// <hand-written-imports>
import org.graylog.kusto.language.symbols.EntityGroupElementSymbol;
import org.graylog.kusto.language.symbols.TupleSymbol;
import org.graylog.kusto.language.symbols.TypeSymbol;
import org.graylog.kusto.language.symbols.VariableSymbol;
// </hand-written-imports>

/**
 * A node in the Kusto syntax that represents an expression
 */
public abstract class Expression extends SyntaxNode {
    /** Constructs a new instance of {@link Expression}. */
    public Expression(List<Diagnostic> diagnostics) {
        super(diagnostics);
    }
    public Expression() { this(null); }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:107-123">
    /// <summary>
    /// True if the expression is a literal.
    /// </summary>
    public boolean isLiteral() { return false; }

    /// <summary>
    /// The value info of the literal expression.
    /// </summary>
    public ValueInfo literalValueInfo() { return null; }

    /// <summary>
    /// The value of the literal expression.
    /// </summary>
    public Object literalValue()
    {
        var info = literalValueInfo(); // PORT: §3.14
        return info != null ? info.value() : null;
    }
    // </hand-written>
    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode_Semantics.cs:233-280">
    /// <summary>
    /// The result type of the expression.
    /// </summary>
    public TypeSymbol resultType()
    {
        var type = this.rawResultType();

        // if only one column, reduce to just the one column's scalar value
        if (type instanceof TupleSymbol ts && ts.columns().size() == 1 && ts.isReducibleToScalar())
        {
            return ts.columns().get(0).type();
        }
        else if (type instanceof EntityGroupElementSymbol eges)
        {
            return eges.underlyingSymbol();
        }

        return type;
    }

    /// <summary>
    /// The unadjusted result type of the expression.
    /// </summary>
    public TypeSymbol rawResultType()
    {
        var info = getSemanticInfo(); // PORT: §3.14
        return info != null ? info.resultType() : null;
    }

    /// <summary>
    /// True if the expression is considered constant.
    /// </summary>
    public boolean isConstant()
    {
        var info = getSemanticInfo(); // PORT: §3.14
        return info != null ? info.isConstant() : false;
    }

    /// <summary>
    /// Returns the value info of the constant, or null if it is unknown.
    /// </summary>
    public ValueInfo constantValueInfo()
    {
        return this.isLiteral() ? this.literalValueInfo()
            : this.referencedSymbol() instanceof VariableSymbol v && v.isConstant() ? v.constantValueInfo()
            : null;
    }

    /// <summary>
    /// The value of the constant or null if it is unknown.
    /// </summary>
    public Object constantValue()
    {
        var info = constantValueInfo(); // PORT: §3.14
        return info != null ? info.value() : null;
    }
    // </hand-written>
}
