// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ExpressionCouple)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a parenthesized pair of expressions.
 */
public final class ExpressionCouple extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ExpressionCouple; }
    private final SyntaxToken openParen;
    /** The open parenthesis token. */
    public SyntaxToken openParen() { return openParen; }
    private final Expression first;
    /** The first expression. */
    public Expression first() { return first; }
    private final SyntaxToken dotDot;
    /** The .. token. */
    public SyntaxToken dotDot() { return dotDot; }
    private final Expression second;
    /** The second expression. */
    public Expression second() { return second; }
    private final SyntaxToken closeParen;
    /** The close parenthesis token. */
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link ExpressionCouple}. */
    public ExpressionCouple(SyntaxToken openParen, Expression first, SyntaxToken dotDot, Expression second, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openParen = attach(openParen);
        this.first = attach(first);
        this.dotDot = attach(dotDot);
        this.second = attach(second);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public ExpressionCouple(SyntaxToken openParen, Expression first, SyntaxToken dotDot, Expression second, SyntaxToken closeParen) { this(openParen, first, dotDot, second, closeParen, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openParen; case 1: return first; case 2: return dotDot; case 3: return second; case 4: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenParen"; case 1: return "First"; case 2: return "DotDot"; case 3: return "Second"; case 4: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Scalar; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Scalar; case 4: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitExpressionCouple(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitExpressionCouple(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ExpressionCouple(openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            first != null ? (Expression) first.clone(includeDiagnostics) : null,
            dotDot != null ? (SyntaxToken) dotDot.clone(includeDiagnostics) : null,
            second != null ? (Expression) second.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
