// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ExternalDataExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ExternalDataExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.ExternalDataExpression; }
    private final SyntaxToken externalDataKeyword;
    public SyntaxToken externalDataKeyword() { return externalDataKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final RowSchema schema;
    public RowSchema schema() { return schema; }
    private final SyntaxToken openBracket;
    public SyntaxToken openBracket() { return openBracket; }
    private final SyntaxList1<SeparatedElement1<Expression>> uRIs;
    public SyntaxList1<SeparatedElement1<Expression>> uRIs() { return uRIs; }
    private final SyntaxToken closeBracket;
    public SyntaxToken closeBracket() { return closeBracket; }
    private final ExternalDataWithClause withClause;
    public ExternalDataWithClause withClause() { return withClause; }

    /** Constructs a new instance of {@link ExternalDataExpression}. */
    public ExternalDataExpression(SyntaxToken externalDataKeyword, SyntaxList1<NamedParameter> parameters, RowSchema schema, SyntaxToken openBracket, SyntaxList1<SeparatedElement1<Expression>> uRIs, SyntaxToken closeBracket, ExternalDataWithClause withClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.externalDataKeyword = attach(externalDataKeyword);
        this.parameters = attach(parameters);
        this.schema = attach(schema);
        this.openBracket = attach(openBracket);
        this.uRIs = attach(uRIs);
        this.closeBracket = attach(closeBracket);
        this.withClause = attach(withClause, true);
        this.init();
    }
    public ExternalDataExpression(SyntaxToken externalDataKeyword, SyntaxList1<NamedParameter> parameters, RowSchema schema, SyntaxToken openBracket, SyntaxList1<SeparatedElement1<Expression>> uRIs, SyntaxToken closeBracket, ExternalDataWithClause withClause) { this(externalDataKeyword, parameters, schema, openBracket, uRIs, closeBracket, withClause, null); }

    @Override public int childCount() { return 7; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return externalDataKeyword; case 1: return parameters; case 2: return schema; case 3: return openBracket; case 4: return uRIs; case 5: return closeBracket; case 6: return withClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ExternalDataKeyword"; case 1: return "Parameters"; case 2: return "Schema"; case 3: return "OpenBracket"; case 4: return "URIs"; case 5: return "CloseBracket"; case 6: return "WithClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 6: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.None; case 5: return CompletionHint.Syntax; case 6: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitExternalDataExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitExternalDataExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ExternalDataExpression(externalDataKeyword != null ? (SyntaxToken) externalDataKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            schema != null ? (RowSchema) schema.clone(includeDiagnostics) : null,
            openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            uRIs != null ? (SyntaxList1<SeparatedElement1<Expression>>) uRIs.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            withClause != null ? (ExternalDataWithClause) withClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
