// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FindOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FindOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.FindOperator; }
    private final SyntaxToken findKeyword;
    public SyntaxToken findKeyword() { return findKeyword; }
    private final DataScopeClause dataScope;
    public DataScopeClause dataScope() { return dataScope; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final FindInClause inClause;
    public FindInClause inClause() { return inClause; }
    private final SyntaxToken whereKeyword;
    public SyntaxToken whereKeyword() { return whereKeyword; }
    private final Expression condition;
    public Expression condition() { return condition; }
    private final FindProjectClause project;
    public FindProjectClause project() { return project; }
    private final FindProjectClause projectAway;
    public FindProjectClause projectAway() { return projectAway; }

    /** Constructs a new instance of {@link FindOperator}. */
    public FindOperator(SyntaxToken findKeyword, DataScopeClause dataScope, SyntaxList1<NamedParameter> parameters, FindInClause inClause, SyntaxToken whereKeyword, Expression condition, FindProjectClause project, FindProjectClause projectAway, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.findKeyword = attach(findKeyword);
        this.dataScope = attach(dataScope, true);
        this.parameters = attach(parameters);
        this.inClause = attach(inClause, true);
        this.whereKeyword = attach(whereKeyword, true);
        this.condition = attach(condition);
        this.project = attach(project, true);
        this.projectAway = attach(projectAway, true);
        this.init();
    }
    public FindOperator(SyntaxToken findKeyword, DataScopeClause dataScope, SyntaxList1<NamedParameter> parameters, FindInClause inClause, SyntaxToken whereKeyword, Expression condition, FindProjectClause project, FindProjectClause projectAway) { this(findKeyword, dataScope, parameters, inClause, whereKeyword, condition, project, projectAway, null); }

    @Override public int childCount() { return 8; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return findKeyword; case 1: return dataScope; case 2: return parameters; case 3: return inClause; case 4: return whereKeyword; case 5: return condition; case 6: return project; case 7: return projectAway; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "FindKeyword"; case 1: return "DataScope"; case 2: return "Parameters"; case 3: return "InClause"; case 4: return "WhereKeyword"; case 5: return "Condition"; case 6: return "Project"; case 7: return "ProjectAway"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: case 3: case 4: case 6: case 7: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Clause; case 2: return CompletionHint.None; case 3: return CompletionHint.Clause; case 4: return CompletionHint.Keyword; case 5: return CompletionHint.Boolean; case 6: return CompletionHint.Clause; case 7: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFindOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFindOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FindOperator(findKeyword != null ? (SyntaxToken) findKeyword.clone(includeDiagnostics) : null,
            dataScope != null ? (DataScopeClause) dataScope.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            inClause != null ? (FindInClause) inClause.clone(includeDiagnostics) : null,
            whereKeyword != null ? (SyntaxToken) whereKeyword.clone(includeDiagnostics) : null,
            condition != null ? (Expression) condition.clone(includeDiagnostics) : null,
            project != null ? (FindProjectClause) project.clone(includeDiagnostics) : null,
            projectAway != null ? (FindProjectClause) projectAway.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
