// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FindProjectClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FindProjectClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.FindProjectClause; }
    private final SyntaxToken projectKeyword;
    public SyntaxToken projectKeyword() { return projectKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> columns;
    public SyntaxList1<SeparatedElement1<Expression>> columns() { return columns; }

    /** Constructs a new instance of {@link FindProjectClause}. */
    public FindProjectClause(SyntaxToken projectKeyword, SyntaxList1<SeparatedElement1<Expression>> columns, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.projectKeyword = attach(projectKeyword);
        this.columns = attach(columns);
        this.init();
    }
    public FindProjectClause(SyntaxToken projectKeyword, SyntaxList1<SeparatedElement1<Expression>> columns) { this(projectKeyword, columns, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return projectKeyword; case 1: return columns; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ProjectKeyword"; case 1: return "Columns"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFindProjectClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFindProjectClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FindProjectClause(projectKeyword != null ? (SyntaxToken) projectKeyword.clone(includeDiagnostics) : null,
            columns != null ? (SyntaxList1<SeparatedElement1<Expression>>) columns.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
