// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ForkOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ForkOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ForkOperator; }
    private final SyntaxToken forkKeyword;
    public SyntaxToken forkKeyword() { return forkKeyword; }
    private final SyntaxList1<ForkExpression> expressions;
    public SyntaxList1<ForkExpression> expressions() { return expressions; }

    /** Constructs a new instance of {@link ForkOperator}. */
    public ForkOperator(SyntaxToken forkKeyword, SyntaxList1<ForkExpression> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.forkKeyword = attach(forkKeyword);
        this.expressions = attach(expressions);
        this.init();
    }
    public ForkOperator(SyntaxToken forkKeyword, SyntaxList1<ForkExpression> expressions) { this(forkKeyword, expressions, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return forkKeyword; case 1: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ForkKeyword"; case 1: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.NonScalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitForkOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitForkOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ForkOperator(forkKeyword != null ? (SyntaxToken) forkKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<ForkExpression>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
