// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FunctionParameter)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FunctionParameter extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.FunctionParameter; }
    private final NameAndTypeDeclaration nameAndType;
    public NameAndTypeDeclaration nameAndType() { return nameAndType; }
    private final DefaultValueDeclaration defaultValue;
    public DefaultValueDeclaration defaultValue() { return defaultValue; }

    /** Constructs a new instance of {@link FunctionParameter}. */
    public FunctionParameter(NameAndTypeDeclaration nameAndType, DefaultValueDeclaration defaultValue, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.nameAndType = attach(nameAndType);
        this.defaultValue = attach(defaultValue, true);
        this.init();
    }
    public FunctionParameter(NameAndTypeDeclaration nameAndType, DefaultValueDeclaration defaultValue) { this(nameAndType, defaultValue, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return nameAndType; case 1: return defaultValue; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "NameAndType"; case 1: return "DefaultValue"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFunctionParameter(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFunctionParameter(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FunctionParameter(nameAndType != null ? (NameAndTypeDeclaration) nameAndType.clone(includeDiagnostics) : null,
            defaultValue != null ? (DefaultValueDeclaration) defaultValue.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
