// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FunctionParameters)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FunctionParameters extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.FunctionParameters; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxList1<SeparatedElement1<FunctionParameter>> parameters;
    public SyntaxList1<SeparatedElement1<FunctionParameter>> parameters() { return parameters; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link FunctionParameters}. */
    public FunctionParameters(SyntaxToken openParen, SyntaxList1<SeparatedElement1<FunctionParameter>> parameters, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openParen = attach(openParen);
        this.parameters = attach(parameters);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public FunctionParameters(SyntaxToken openParen, SyntaxList1<SeparatedElement1<FunctionParameter>> parameters, SyntaxToken closeParen) { this(openParen, parameters, closeParen, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openParen; case 1: return parameters; case 2: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenParen"; case 1: return "Parameters"; case 2: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFunctionParameters(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFunctionParameters(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FunctionParameters(openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<SeparatedElement1<FunctionParameter>>) parameters.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
