// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FunctionBody)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FunctionBody extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.FunctionBody; }
    private final SyntaxToken openBrace;
    public SyntaxToken openBrace() { return openBrace; }
    private final SyntaxList1<SeparatedElement1<Statement>> statements;
    public SyntaxList1<SeparatedElement1<Statement>> statements() { return statements; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken semicolon;
    public SyntaxToken semicolon() { return semicolon; }
    private final SyntaxToken closeBrace;
    public SyntaxToken closeBrace() { return closeBrace; }

    /** Constructs a new instance of {@link FunctionBody}. */
    public FunctionBody(SyntaxToken openBrace, SyntaxList1<SeparatedElement1<Statement>> statements, Expression expression, SyntaxToken semicolon, SyntaxToken closeBrace, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBrace = attach(openBrace);
        this.statements = attach(statements);
        this.expression = attach(expression, true);
        this.semicolon = attach(semicolon, true);
        this.closeBrace = attach(closeBrace);
        this.init();
    }
    public FunctionBody(SyntaxToken openBrace, SyntaxList1<SeparatedElement1<Statement>> statements, Expression expression, SyntaxToken semicolon, SyntaxToken closeBrace) { this(openBrace, statements, expression, semicolon, closeBrace, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBrace; case 1: return statements; case 2: return expression; case 3: return semicolon; case 4: return closeBrace; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBrace"; case 1: return "Statements"; case 2: return "Expression"; case 3: return "Semicolon"; case 4: return "CloseBrace"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 2: case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.NonScalar; case 2: return CompletionHint.Expression; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFunctionBody(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFunctionBody(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FunctionBody(openBrace != null ? (SyntaxToken) openBrace.clone(includeDiagnostics) : null,
            statements != null ? (SyntaxList1<SeparatedElement1<Statement>>) statements.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            semicolon != null ? (SyntaxToken) semicolon.clone(includeDiagnostics) : null,
            closeBrace != null ? (SyntaxToken) closeBrace.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
