// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node FunctionDeclaration)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class FunctionDeclaration extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.FunctionDeclaration; }
    private final SyntaxToken viewKeyword;
    public SyntaxToken viewKeyword() { return viewKeyword; }
    private final FunctionParameters parameters;
    public FunctionParameters parameters() { return parameters; }
    private final FunctionBody body;
    public FunctionBody body() { return body; }

    /** Constructs a new instance of {@link FunctionDeclaration}. */
    public FunctionDeclaration(SyntaxToken viewKeyword, FunctionParameters parameters, FunctionBody body, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.viewKeyword = attach(viewKeyword, true);
        this.parameters = attach(parameters);
        this.body = attach(body);
        this.init();
    }
    public FunctionDeclaration(SyntaxToken viewKeyword, FunctionParameters parameters, FunctionBody body) { this(viewKeyword, parameters, body, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return viewKeyword; case 1: return parameters; case 2: return body; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ViewKeyword"; case 1: return "Parameters"; case 2: return "Body"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 0: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitFunctionDeclaration(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitFunctionDeclaration(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new FunctionDeclaration(viewKeyword != null ? (SyntaxToken) viewKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (FunctionParameters) parameters.clone(includeDiagnostics) : null,
            body != null ? (FunctionBody) body.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
