// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphMarkComponentsOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphMarkComponentsOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphMarkComponentsOperator; }
    private final SyntaxToken graphMarkComponentsKeyword;
    public SyntaxToken graphMarkComponentsKeyword() { return graphMarkComponentsKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }

    /** Constructs a new instance of {@link GraphMarkComponentsOperator}. */
    public GraphMarkComponentsOperator(SyntaxToken graphMarkComponentsKeyword, SyntaxList1<NamedParameter> parameters, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.graphMarkComponentsKeyword = attach(graphMarkComponentsKeyword);
        this.parameters = attach(parameters);
        this.init();
    }
    public GraphMarkComponentsOperator(SyntaxToken graphMarkComponentsKeyword, SyntaxList1<NamedParameter> parameters) { this(graphMarkComponentsKeyword, parameters, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return graphMarkComponentsKeyword; case 1: return parameters; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "GraphMarkComponentsKeyword"; case 1: return "Parameters"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphMarkComponentsOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphMarkComponentsOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphMarkComponentsOperator(graphMarkComponentsKeyword != null ? (SyntaxToken) graphMarkComponentsKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
