// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphWhereNodesOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphWhereNodesOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphWhereNodesOperator; }
    private final SyntaxToken graphWhereNodesKeyword;
    public SyntaxToken graphWhereNodesKeyword() { return graphWhereNodesKeyword; }
    private final Expression condition;
    public Expression condition() { return condition; }

    /** Constructs a new instance of {@link GraphWhereNodesOperator}. */
    public GraphWhereNodesOperator(SyntaxToken graphWhereNodesKeyword, Expression condition, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.graphWhereNodesKeyword = attach(graphWhereNodesKeyword);
        this.condition = attach(condition);
        this.init();
    }
    public GraphWhereNodesOperator(SyntaxToken graphWhereNodesKeyword, Expression condition) { this(graphWhereNodesKeyword, condition, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return graphWhereNodesKeyword; case 1: return condition; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "GraphWhereNodesKeyword"; case 1: return "Condition"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Boolean; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphWhereNodesOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphWhereNodesOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphWhereNodesOperator(graphWhereNodesKeyword != null ? (SyntaxToken) graphWhereNodesKeyword.clone(includeDiagnostics) : null,
            condition != null ? (Expression) condition.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
