// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphMatchPatternEdge)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphMatchPatternEdge extends GraphMatchPatternNotation {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphMatchPatternEdge; }
    private final SyntaxToken firstToken;
    public SyntaxToken firstToken() { return firstToken; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final GraphMatchPatternEdgeRange range;
    public GraphMatchPatternEdgeRange range() { return range; }
    private final SyntaxToken lastToken;
    public SyntaxToken lastToken() { return lastToken; }

    /** Constructs a new instance of {@link GraphMatchPatternEdge}. */
    public GraphMatchPatternEdge(SyntaxToken firstToken, NameDeclaration name, GraphMatchPatternEdgeRange range, SyntaxToken lastToken, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.firstToken = attach(firstToken);
        this.name = attach(name, true);
        this.range = attach(range, true);
        this.lastToken = attach(lastToken, true);
        this.init();
    }
    public GraphMatchPatternEdge(SyntaxToken firstToken, NameDeclaration name, GraphMatchPatternEdgeRange range, SyntaxToken lastToken) { this(firstToken, name, range, lastToken, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return firstToken; case 1: return name; case 2: return range; case 3: return lastToken; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "FirstToken"; case 1: return "Name"; case 2: return "Range"; case 3: return "LastToken"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: case 2: case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.None; case 2: return CompletionHint.None; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphMatchPatternEdge(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphMatchPatternEdge(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphMatchPatternEdge(firstToken != null ? (SyntaxToken) firstToken.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            range != null ? (GraphMatchPatternEdgeRange) range.clone(includeDiagnostics) : null,
            lastToken != null ? (SyntaxToken) lastToken.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
