// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphMatchPatternNode)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphMatchPatternNode extends GraphMatchPatternNotation {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphMatchPatternNode; }
    private final SyntaxToken open;
    public SyntaxToken open() { return open; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final SyntaxToken close;
    public SyntaxToken close() { return close; }

    /** Constructs a new instance of {@link GraphMatchPatternNode}. */
    public GraphMatchPatternNode(SyntaxToken open, NameDeclaration name, SyntaxToken close, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.open = attach(open);
        this.name = attach(name, true);
        this.close = attach(close);
        this.init();
    }
    public GraphMatchPatternNode(SyntaxToken open, NameDeclaration name, SyntaxToken close) { this(open, name, close, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return open; case 1: return name; case 2: return close; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Open"; case 1: return "Name"; case 2: return "Close"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Keyword; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphMatchPatternNode(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphMatchPatternNode(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphMatchPatternNode(open != null ? (SyntaxToken) open.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            close != null ? (SyntaxToken) close.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
