// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphMatchPatternEdgeRange)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphMatchPatternEdgeRange extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphMatchPatternEdgeRange; }
    private final SyntaxToken asterisk;
    public SyntaxToken asterisk() { return asterisk; }
    private final Expression rangeStart;
    public Expression rangeStart() { return rangeStart; }
    private final SyntaxToken dotDotToken;
    public SyntaxToken dotDotToken() { return dotDotToken; }
    private final Expression rangeEnd;
    public Expression rangeEnd() { return rangeEnd; }

    /** Constructs a new instance of {@link GraphMatchPatternEdgeRange}. */
    public GraphMatchPatternEdgeRange(SyntaxToken asterisk, Expression rangeStart, SyntaxToken dotDotToken, Expression rangeEnd, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.asterisk = attach(asterisk);
        this.rangeStart = attach(rangeStart);
        this.dotDotToken = attach(dotDotToken);
        this.rangeEnd = attach(rangeEnd);
        this.init();
    }
    public GraphMatchPatternEdgeRange(SyntaxToken asterisk, Expression rangeStart, SyntaxToken dotDotToken, Expression rangeEnd) { this(asterisk, rangeStart, dotDotToken, rangeEnd, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return asterisk; case 1: return rangeStart; case 2: return dotDotToken; case 3: return rangeEnd; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Asterisk"; case 1: return "RangeStart"; case 2: return "DotDotToken"; case 3: return "RangeEnd"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Scalar; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphMatchPatternEdgeRange(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphMatchPatternEdgeRange(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphMatchPatternEdgeRange(asterisk != null ? (SyntaxToken) asterisk.clone(includeDiagnostics) : null,
            rangeStart != null ? (Expression) rangeStart.clone(includeDiagnostics) : null,
            dotDotToken != null ? (SyntaxToken) dotDotToken.clone(includeDiagnostics) : null,
            rangeEnd != null ? (Expression) rangeEnd.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
