// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphMatchOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphMatchOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphMatchOperator; }
    private final SyntaxToken graphMatchKeyword;
    public SyntaxToken graphMatchKeyword() { return graphMatchKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<GraphMatchPattern>> patterns;
    public SyntaxList1<SeparatedElement1<GraphMatchPattern>> patterns() { return patterns; }
    private final WhereClause whereClause;
    public WhereClause whereClause() { return whereClause; }
    private final ProjectClause projectClause;
    public ProjectClause projectClause() { return projectClause; }

    /** Constructs a new instance of {@link GraphMatchOperator}. */
    public GraphMatchOperator(SyntaxToken graphMatchKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<GraphMatchPattern>> patterns, WhereClause whereClause, ProjectClause projectClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.graphMatchKeyword = attach(graphMatchKeyword);
        this.parameters = attach(parameters);
        this.patterns = attach(patterns);
        this.whereClause = attach(whereClause, true);
        this.projectClause = attach(projectClause, true);
        this.init();
    }
    public GraphMatchOperator(SyntaxToken graphMatchKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<GraphMatchPattern>> patterns, WhereClause whereClause, ProjectClause projectClause) { this(graphMatchKeyword, parameters, patterns, whereClause, projectClause, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return graphMatchKeyword; case 1: return parameters; case 2: return patterns; case 3: return whereClause; case 4: return projectClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "GraphMatchKeyword"; case 1: return "Parameters"; case 2: return "Patterns"; case 3: return "WhereClause"; case 4: return "ProjectClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphMatchOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphMatchOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphMatchOperator(graphMatchKeyword != null ? (SyntaxToken) graphMatchKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            patterns != null ? (SyntaxList1<SeparatedElement1<GraphMatchPattern>>) patterns.clone(includeDiagnostics) : null,
            whereClause != null ? (WhereClause) whereClause.clone(includeDiagnostics) : null,
            projectClause != null ? (ProjectClause) projectClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
