// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphToTableOutputClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphToTableOutputClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphToTableOutputClause; }
    private final SyntaxToken entityKeyword;
    public SyntaxToken entityKeyword() { return entityKeyword; }
    private final GraphToTableAsClause asClause;
    public GraphToTableAsClause asClause() { return asClause; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }

    /** Constructs a new instance of {@link GraphToTableOutputClause}. */
    public GraphToTableOutputClause(SyntaxToken entityKeyword, GraphToTableAsClause asClause, SyntaxList1<NamedParameter> parameters, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.entityKeyword = attach(entityKeyword);
        this.asClause = attach(asClause, true);
        this.parameters = attach(parameters, true);
        this.init();
    }
    public GraphToTableOutputClause(SyntaxToken entityKeyword, GraphToTableAsClause asClause, SyntaxList1<NamedParameter> parameters) { this(entityKeyword, asClause, parameters, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return entityKeyword; case 1: return asClause; case 2: return parameters; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "EntityKeyword"; case 1: return "AsClause"; case 2: return "Parameters"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: case 2: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphToTableOutputClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphToTableOutputClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphToTableOutputClause(entityKeyword != null ? (SyntaxToken) entityKeyword.clone(includeDiagnostics) : null,
            asClause != null ? (GraphToTableAsClause) asClause.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
