// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node GraphToTableOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class GraphToTableOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.GraphToTableOperator; }
    private final SyntaxToken graphToTableKeyword;
    public SyntaxToken graphToTableKeyword() { return graphToTableKeyword; }
    private final SyntaxList1<SeparatedElement1<GraphToTableOutputClause>> outputClause;
    public SyntaxList1<SeparatedElement1<GraphToTableOutputClause>> outputClause() { return outputClause; }

    /** Constructs a new instance of {@link GraphToTableOperator}. */
    public GraphToTableOperator(SyntaxToken graphToTableKeyword, SyntaxList1<SeparatedElement1<GraphToTableOutputClause>> outputClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.graphToTableKeyword = attach(graphToTableKeyword);
        this.outputClause = attach(outputClause);
        this.init();
    }
    public GraphToTableOperator(SyntaxToken graphToTableKeyword, SyntaxList1<SeparatedElement1<GraphToTableOutputClause>> outputClause) { this(graphToTableKeyword, outputClause, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return graphToTableKeyword; case 1: return outputClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "GraphToTableKeyword"; case 1: return "OutputClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitGraphToTableOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitGraphToTableOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new GraphToTableOperator(graphToTableKeyword != null ? (SyntaxToken) graphToTableKeyword.clone(includeDiagnostics) : null,
            outputClause != null ? (SyntaxList1<SeparatedElement1<GraphToTableOutputClause>>) outputClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
