// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node HasAnyExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a has_any expression.
 */
public final class HasAnyExpression extends Expression {
    private final SyntaxKind kind;
    @Override public SyntaxKind kind() { return this.kind; }
    private final Expression left;
    /** The left side expression. */
    public Expression left() { return left; }
    private final SyntaxToken operator;
    /** The has_any keyword. */
    public SyntaxToken operator() { return operator; }
    private final ExpressionList right;
    /** The list of expressions. */
    public ExpressionList right() { return right; }

    /** Constructs a new instance of {@link HasAnyExpression}. */
    public HasAnyExpression(SyntaxKind kind, Expression left, SyntaxToken operator, ExpressionList right, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.kind = kind;
        this.left = attach(left);
        this.operator = attach(operator);
        this.right = attach(right);
        this.init();
    }
    public HasAnyExpression(SyntaxKind kind, Expression left, SyntaxToken operator, ExpressionList right) { this(kind, left, operator, right, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return left; case 1: return operator; case 2: return right; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Left"; case 1: return "Operator"; case 2: return "Right"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitHasAnyExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitHasAnyExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new HasAnyExpression(this.kind(), left != null ? (Expression) left.clone(includeDiagnostics) : null,
            operator != null ? (SyntaxToken) operator.clone(includeDiagnostics) : null,
            right != null ? (ExpressionList) right.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
