// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node InlineExternalTablePathFormatPartitionColumnReference)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class InlineExternalTablePathFormatPartitionColumnReference extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.InlineExternalTablePathFormatPartitionColumnReference; }
    private final Expression partitionColumnExpression;
    public Expression partitionColumnExpression() { return partitionColumnExpression; }
    private final LiteralExpression separatorLiteral;
    public LiteralExpression separatorLiteral() { return separatorLiteral; }

    /** Constructs a new instance of {@link InlineExternalTablePathFormatPartitionColumnReference}. */
    public InlineExternalTablePathFormatPartitionColumnReference(Expression partitionColumnExpression, LiteralExpression separatorLiteral, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.partitionColumnExpression = attach(partitionColumnExpression);
        this.separatorLiteral = attach(separatorLiteral, true);
        this.init();
    }
    public InlineExternalTablePathFormatPartitionColumnReference(Expression partitionColumnExpression, LiteralExpression separatorLiteral) { this(partitionColumnExpression, separatorLiteral, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return partitionColumnExpression; case 1: return separatorLiteral; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PartitionColumnExpression"; case 1: return "SeparatorLiteral"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Column; case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitInlineExternalTablePathFormatPartitionColumnReference(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitInlineExternalTablePathFormatPartitionColumnReference(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new InlineExternalTablePathFormatPartitionColumnReference(partitionColumnExpression != null ? (Expression) partitionColumnExpression.clone(includeDiagnostics) : null,
            separatorLiteral != null ? (LiteralExpression) separatorLiteral.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
