// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node InlineExternalTablePartitionClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A clause that specifies the partitioning for inline external table.
 */
public final class InlineExternalTablePartitionClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.InlineExternalTablePartitionClause; }
    private final SyntaxToken partitionKeyword;
    public SyntaxToken partitionKeyword() { return partitionKeyword; }
    private final SyntaxToken byKeyword;
    public SyntaxToken byKeyword() { return byKeyword; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxToken leadingComma;
    public SyntaxToken leadingComma() { return leadingComma; }
    private final SyntaxList1<SeparatedElement1<PartitionColumnDeclaration>> partitionColumns;
    public SyntaxList1<SeparatedElement1<PartitionColumnDeclaration>> partitionColumns() { return partitionColumns; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link InlineExternalTablePartitionClause}. */
    public InlineExternalTablePartitionClause(SyntaxToken partitionKeyword, SyntaxToken byKeyword, SyntaxToken openParen, SyntaxToken leadingComma, SyntaxList1<SeparatedElement1<PartitionColumnDeclaration>> partitionColumns, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.partitionKeyword = attach(partitionKeyword);
        this.byKeyword = attach(byKeyword);
        this.openParen = attach(openParen);
        this.leadingComma = attach(leadingComma, true);
        this.partitionColumns = attach(partitionColumns);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public InlineExternalTablePartitionClause(SyntaxToken partitionKeyword, SyntaxToken byKeyword, SyntaxToken openParen, SyntaxToken leadingComma, SyntaxList1<SeparatedElement1<PartitionColumnDeclaration>> partitionColumns, SyntaxToken closeParen) { this(partitionKeyword, byKeyword, openParen, leadingComma, partitionColumns, closeParen, null); }

    @Override public int childCount() { return 6; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return partitionKeyword; case 1: return byKeyword; case 2: return openParen; case 3: return leadingComma; case 4: return partitionColumns; case 5: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PartitionKeyword"; case 1: return "ByKeyword"; case 2: return "OpenParen"; case 3: return "LeadingComma"; case 4: return "PartitionColumns"; case 5: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Keyword; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Declaration; case 5: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitInlineExternalTablePartitionClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitInlineExternalTablePartitionClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new InlineExternalTablePartitionClause(partitionKeyword != null ? (SyntaxToken) partitionKeyword.clone(includeDiagnostics) : null,
            byKeyword != null ? (SyntaxToken) byKeyword.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            leadingComma != null ? (SyntaxToken) leadingComma.clone(includeDiagnostics) : null,
            partitionColumns != null ? (SyntaxList1<SeparatedElement1<PartitionColumnDeclaration>>) partitionColumns.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
