// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node InlineExternalTableDataFormatClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class InlineExternalTableDataFormatClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.InlineExternalTableDataFormatClause; }
    private final SyntaxToken dataFormatKeyword;
    public SyntaxToken dataFormatKeyword() { return dataFormatKeyword; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final SyntaxToken value;
    public SyntaxToken value() { return value; }

    /** Constructs a new instance of {@link InlineExternalTableDataFormatClause}. */
    public InlineExternalTableDataFormatClause(SyntaxToken dataFormatKeyword, SyntaxToken equalToken, SyntaxToken value, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.dataFormatKeyword = attach(dataFormatKeyword);
        this.equalToken = attach(equalToken);
        this.value = attach(value);
        this.init();
    }
    public InlineExternalTableDataFormatClause(SyntaxToken dataFormatKeyword, SyntaxToken equalToken, SyntaxToken value) { this(dataFormatKeyword, equalToken, value, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return dataFormatKeyword; case 1: return equalToken; case 2: return value; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "DataFormatKeyword"; case 1: return "EqualToken"; case 2: return "Value"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Keyword; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitInlineExternalTableDataFormatClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitInlineExternalTableDataFormatClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new InlineExternalTableDataFormatClause(dataFormatKeyword != null ? (SyntaxToken) dataFormatKeyword.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            value != null ? (SyntaxToken) value.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
