// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node InvokeOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class InvokeOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.InvokeOperator; }
    private final SyntaxToken invokeKeyword;
    public SyntaxToken invokeKeyword() { return invokeKeyword; }
    private final Expression function;
    public Expression function() { return function; }

    /** Constructs a new instance of {@link InvokeOperator}. */
    public InvokeOperator(SyntaxToken invokeKeyword, Expression function, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.invokeKeyword = attach(invokeKeyword);
        this.function = attach(function);
        this.init();
    }
    public InvokeOperator(SyntaxToken invokeKeyword, Expression function) { this(invokeKeyword, function, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return invokeKeyword; case 1: return function; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "InvokeKeyword"; case 1: return "Function"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.TabularFunction; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitInvokeOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitInvokeOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new InvokeOperator(invokeKeyword != null ? (SyntaxToken) invokeKeyword.clone(includeDiagnostics) : null,
            function != null ? (Expression) function.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
