// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node JoinWhereClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class JoinWhereClause extends JoinConditionClause {
    @Override public SyntaxKind kind() { return SyntaxKind.JoinWhereClause; }
    private final SyntaxToken whereKeyword;
    public SyntaxToken whereKeyword() { return whereKeyword; }
    private final Expression expression;
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link JoinWhereClause}. */
    public JoinWhereClause(SyntaxToken whereKeyword, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.whereKeyword = attach(whereKeyword);
        this.expression = attach(expression);
        this.init();
    }
    public JoinWhereClause(SyntaxToken whereKeyword, Expression expression) { this(whereKeyword, expression, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return whereKeyword; case 1: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "WhereKeyword"; case 1: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Boolean; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitJoinWhereClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitJoinWhereClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new JoinWhereClause(whereKeyword != null ? (SyntaxToken) whereKeyword.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
