// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node JoinConditionClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

public abstract class JoinConditionClause extends Clause {
    /** Constructs a new instance of {@link JoinConditionClause}. */
    public JoinConditionClause(List<Diagnostic> diagnostics) {
        super(diagnostics);
    }
    public JoinConditionClause() { this(null); }
}
