// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node JoinOnClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class JoinOnClause extends JoinConditionClause {
    @Override public SyntaxKind kind() { return SyntaxKind.JoinOnClause; }
    private final SyntaxToken onKeyword;
    public SyntaxToken onKeyword() { return onKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }

    /** Constructs a new instance of {@link JoinOnClause}. */
    public JoinOnClause(SyntaxToken onKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.onKeyword = attach(onKeyword);
        this.expressions = attach(expressions);
        this.init();
    }
    public JoinOnClause(SyntaxToken onKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions) { this(onKeyword, expressions, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return onKeyword; case 1: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OnKeyword"; case 1: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Column; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitJoinOnClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitJoinOnClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new JoinOnClause(onKeyword != null ? (SyntaxToken) onKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
