// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node JsonObjectExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a JSON object expression.
 */
public final class JsonObjectExpression extends JsonExpression {
    @Override public SyntaxKind kind() { return SyntaxKind.JsonObjectExpression; }
    private final SyntaxToken openBrace;
    /** The open brace token. */
    public SyntaxToken openBrace() { return openBrace; }
    private final SyntaxList1<SeparatedElement1<JsonPair>> pairs;
    /** The list of name value pairs. */
    public SyntaxList1<SeparatedElement1<JsonPair>> pairs() { return pairs; }
    private final SyntaxToken closeBrace;
    /** The close brace token. */
    public SyntaxToken closeBrace() { return closeBrace; }

    /** Constructs a new instance of {@link JsonObjectExpression}. */
    public JsonObjectExpression(SyntaxToken openBrace, SyntaxList1<SeparatedElement1<JsonPair>> pairs, SyntaxToken closeBrace, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBrace = attach(openBrace);
        this.pairs = attach(pairs);
        this.closeBrace = attach(closeBrace);
        this.init();
    }
    public JsonObjectExpression(SyntaxToken openBrace, SyntaxList1<SeparatedElement1<JsonPair>> pairs, SyntaxToken closeBrace) { this(openBrace, pairs, closeBrace, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBrace; case 1: return pairs; case 2: return closeBrace; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBrace"; case 1: return "Pairs"; case 2: return "CloseBrace"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitJsonObjectExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitJsonObjectExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new JsonObjectExpression(openBrace != null ? (SyntaxToken) openBrace.clone(includeDiagnostics) : null,
            pairs != null ? (SyntaxList1<SeparatedElement1<JsonPair>>) pairs.clone(includeDiagnostics) : null,
            closeBrace != null ? (SyntaxToken) closeBrace.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
