// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node JsonPair)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a JSON scalar expression.
 */
public final class JsonPair extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.JsonPair; }
    private final SyntaxToken name;
    /** The token with the name of the JSON element. */
    public SyntaxToken name() { return name; }
    private final SyntaxToken colon;
    /** The colon token. */
    public SyntaxToken colon() { return colon; }
    private final Expression value;
    /** The value of the JSON element. */
    public Expression value() { return value; }

    /** Constructs a new instance of {@link JsonPair}. */
    public JsonPair(SyntaxToken name, SyntaxToken colon, Expression value, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.name = attach(name);
        this.colon = attach(colon);
        this.value = attach(value);
        this.init();
    }
    public JsonPair(SyntaxToken name, SyntaxToken colon, Expression value) { this(name, colon, value, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return name; case 1: return colon; case 2: return value; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Name"; case 1: return "Colon"; case 2: return "Value"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Declaration; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Literal; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitJsonPair(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitJsonPair(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new JsonPair(name != null ? (SyntaxToken) name.clone(includeDiagnostics) : null,
            colon != null ? (SyntaxToken) colon.clone(includeDiagnostics) : null,
            value != null ? (Expression) value.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
