// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node LetStatement)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class LetStatement extends Statement {
    @Override public SyntaxKind kind() { return SyntaxKind.LetStatement; }
    private final SyntaxToken letKeyword;
    public SyntaxToken letKeyword() { return letKeyword; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final SyntaxToken equal;
    public SyntaxToken equal() { return equal; }
    private final Expression expression;
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link LetStatement}. */
    public LetStatement(SyntaxToken letKeyword, NameDeclaration name, SyntaxToken equal, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.letKeyword = attach(letKeyword);
        this.name = attach(name);
        this.equal = attach(equal);
        this.expression = attach(expression);
        this.init();
    }
    public LetStatement(SyntaxToken letKeyword, NameDeclaration name, SyntaxToken equal, Expression expression) { this(letKeyword, name, equal, expression, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return letKeyword; case 1: return name; case 2: return equal; case 3: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "LetKeyword"; case 1: return "Name"; case 2: return "Equal"; case 3: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Declaration; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Expression; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitLetStatement(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitLetStatement(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new LetStatement(letKeyword != null ? (SyntaxToken) letKeyword.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            equal != null ? (SyntaxToken) equal.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
