// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node LiteralExpression)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

/**
 * A node in the kusto syntax that represents a literal expression.
 */
public final class LiteralExpression extends Expression {
    private final SyntaxKind kind;
    @Override public SyntaxKind kind() { return this.kind; }
    private final SyntaxToken token;
    /** The token with the literal value. */
    public SyntaxToken token() { return token; }

    /** Constructs a new instance of {@link LiteralExpression}. */
    public LiteralExpression(SyntaxKind kind, SyntaxToken token, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.kind = kind;
        this.token = attach(token);
        this.init();
    }
    public LiteralExpression(SyntaxKind kind, SyntaxToken token) { this(kind, token, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return token; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Token"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Literal; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitLiteralExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitLiteralExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new LiteralExpression(this.kind(), token != null ? (SyntaxToken) token.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:125-131">
    @Override
    public boolean isLiteral() { return true; }

    @Override
    public ValueInfo literalValueInfo()
    {
        return new ValueInfo(this.token().text(), this.token().valueText(), this.token().value());
    }
    // </hand-written>
}
