// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MakeGraphTableAndKeyClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MakeGraphTableAndKeyClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.MakeGraphTableAndKeyClause; }
    private final Expression table;
    public Expression table() { return table; }
    private final SyntaxToken onKeyword;
    public SyntaxToken onKeyword() { return onKeyword; }
    private final NameReference column;
    public NameReference column() { return column; }

    /** Constructs a new instance of {@link MakeGraphTableAndKeyClause}. */
    public MakeGraphTableAndKeyClause(Expression table, SyntaxToken onKeyword, NameReference column, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.table = attach(table);
        this.onKeyword = attach(onKeyword);
        this.column = attach(column);
        this.init();
    }
    public MakeGraphTableAndKeyClause(Expression table, SyntaxToken onKeyword, NameReference column) { this(table, onKeyword, column, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return table; case 1: return onKeyword; case 2: return column; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Table"; case 1: return "OnKeyword"; case 2: return "Column"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.NonScalar; case 1: return CompletionHint.Keyword; case 2: return CompletionHint.Column; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMakeGraphTableAndKeyClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMakeGraphTableAndKeyClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MakeGraphTableAndKeyClause(table != null ? (Expression) table.clone(includeDiagnostics) : null,
            onKeyword != null ? (SyntaxToken) onKeyword.clone(includeDiagnostics) : null,
            column != null ? (NameReference) column.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
