// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MakeSeriesInRangeClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MakeSeriesInRangeClause extends MakeSeriesRangeClause {
    @Override public SyntaxKind kind() { return SyntaxKind.MakeSeriesInRangeClause; }
    private final SyntaxToken inKeyword;
    public SyntaxToken inKeyword() { return inKeyword; }
    private final SyntaxToken rangeKeyword;
    public SyntaxToken rangeKeyword() { return rangeKeyword; }
    private final ExpressionList arguments;
    public ExpressionList arguments() { return arguments; }

    /** Constructs a new instance of {@link MakeSeriesInRangeClause}. */
    public MakeSeriesInRangeClause(SyntaxToken inKeyword, SyntaxToken rangeKeyword, ExpressionList arguments, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.inKeyword = attach(inKeyword);
        this.rangeKeyword = attach(rangeKeyword);
        this.arguments = attach(arguments);
        this.init();
    }
    public MakeSeriesInRangeClause(SyntaxToken inKeyword, SyntaxToken rangeKeyword, ExpressionList arguments) { this(inKeyword, rangeKeyword, arguments, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return inKeyword; case 1: return rangeKeyword; case 2: return arguments; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "InKeyword"; case 1: return "RangeKeyword"; case 2: return "Arguments"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Keyword; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMakeSeriesInRangeClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMakeSeriesInRangeClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MakeSeriesInRangeClause(inKeyword != null ? (SyntaxToken) inKeyword.clone(includeDiagnostics) : null,
            rangeKeyword != null ? (SyntaxToken) rangeKeyword.clone(includeDiagnostics) : null,
            arguments != null ? (ExpressionList) arguments.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
