// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MakeGraphWithImplicitIdClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MakeGraphWithImplicitIdClause extends MakeGraphWithClause {
    @Override public SyntaxKind kind() { return SyntaxKind.MakeGraphWithImplicitIdClause; }
    private final SyntaxToken withNodeIdKeyword;
    public SyntaxToken withNodeIdKeyword() { return withNodeIdKeyword; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }

    /** Constructs a new instance of {@link MakeGraphWithImplicitIdClause}. */
    public MakeGraphWithImplicitIdClause(SyntaxToken withNodeIdKeyword, SyntaxToken equalToken, NameDeclaration name, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.withNodeIdKeyword = attach(withNodeIdKeyword);
        this.equalToken = attach(equalToken);
        this.name = attach(name);
        this.init();
    }
    public MakeGraphWithImplicitIdClause(SyntaxToken withNodeIdKeyword, SyntaxToken equalToken, NameDeclaration name) { this(withNodeIdKeyword, equalToken, name, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return withNodeIdKeyword; case 1: return equalToken; case 2: return name; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "WithNodeIdKeyword"; case 1: return "EqualToken"; case 2: return "Name"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Declaration; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMakeGraphWithImplicitIdClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMakeGraphWithImplicitIdClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MakeGraphWithImplicitIdClause(withNodeIdKeyword != null ? (SyntaxToken) withNodeIdKeyword.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
