// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MakeGraphOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MakeGraphOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.MakeGraphOperator; }
    private final SyntaxToken makeGraphKeyword;
    public SyntaxToken makeGraphKeyword() { return makeGraphKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final NameReference sourceColumn;
    public NameReference sourceColumn() { return sourceColumn; }
    private final SyntaxToken directionToken;
    public SyntaxToken directionToken() { return directionToken; }
    private final NameReference targetColumn;
    public NameReference targetColumn() { return targetColumn; }
    private final MakeGraphWithClause withClause;
    public MakeGraphWithClause withClause() { return withClause; }
    private final MakeGraphPartitionedByClause partitionedByClause;
    public MakeGraphPartitionedByClause partitionedByClause() { return partitionedByClause; }

    /** Constructs a new instance of {@link MakeGraphOperator}. */
    public MakeGraphOperator(SyntaxToken makeGraphKeyword, SyntaxList1<NamedParameter> parameters, NameReference sourceColumn, SyntaxToken directionToken, NameReference targetColumn, MakeGraphWithClause withClause, MakeGraphPartitionedByClause partitionedByClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.makeGraphKeyword = attach(makeGraphKeyword);
        this.parameters = attach(parameters);
        this.sourceColumn = attach(sourceColumn);
        this.directionToken = attach(directionToken);
        this.targetColumn = attach(targetColumn);
        this.withClause = attach(withClause, true);
        this.partitionedByClause = attach(partitionedByClause, true);
        this.init();
    }
    public MakeGraphOperator(SyntaxToken makeGraphKeyword, SyntaxList1<NamedParameter> parameters, NameReference sourceColumn, SyntaxToken directionToken, NameReference targetColumn, MakeGraphWithClause withClause, MakeGraphPartitionedByClause partitionedByClause) { this(makeGraphKeyword, parameters, sourceColumn, directionToken, targetColumn, withClause, partitionedByClause, null); }

    @Override public int childCount() { return 7; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return makeGraphKeyword; case 1: return parameters; case 2: return sourceColumn; case 3: return directionToken; case 4: return targetColumn; case 5: return withClause; case 6: return partitionedByClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "MakeGraphKeyword"; case 1: return "Parameters"; case 2: return "SourceColumn"; case 3: return "DirectionToken"; case 4: return "TargetColumn"; case 5: return "WithClause"; case 6: return "PartitionedByClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 5: case 6: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Column; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Column; case 5: return CompletionHint.Clause; case 6: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMakeGraphOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMakeGraphOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MakeGraphOperator(makeGraphKeyword != null ? (SyntaxToken) makeGraphKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            sourceColumn != null ? (NameReference) sourceColumn.clone(includeDiagnostics) : null,
            directionToken != null ? (SyntaxToken) directionToken.clone(includeDiagnostics) : null,
            targetColumn != null ? (NameReference) targetColumn.clone(includeDiagnostics) : null,
            withClause != null ? (MakeGraphWithClause) withClause.clone(includeDiagnostics) : null,
            partitionedByClause != null ? (MakeGraphPartitionedByClause) partitionedByClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
