// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MakeSeriesOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MakeSeriesOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.MakeSeriesOperator; }
    private final SyntaxToken makeSeriesKeyword;
    public SyntaxToken makeSeriesKeyword() { return makeSeriesKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<MakeSeriesExpression>> aggregates;
    public SyntaxList1<SeparatedElement1<MakeSeriesExpression>> aggregates() { return aggregates; }
    private final MakeSeriesOnClause onClause;
    public MakeSeriesOnClause onClause() { return onClause; }
    private final MakeSeriesRangeClause rangeClause;
    public MakeSeriesRangeClause rangeClause() { return rangeClause; }
    private final MakeSeriesByClause byClause;
    public MakeSeriesByClause byClause() { return byClause; }

    /** Constructs a new instance of {@link MakeSeriesOperator}. */
    public MakeSeriesOperator(SyntaxToken makeSeriesKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MakeSeriesExpression>> aggregates, MakeSeriesOnClause onClause, MakeSeriesRangeClause rangeClause, MakeSeriesByClause byClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.makeSeriesKeyword = attach(makeSeriesKeyword);
        this.parameters = attach(parameters);
        this.aggregates = attach(aggregates);
        this.onClause = attach(onClause);
        this.rangeClause = attach(rangeClause);
        this.byClause = attach(byClause, true);
        this.init();
    }
    public MakeSeriesOperator(SyntaxToken makeSeriesKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MakeSeriesExpression>> aggregates, MakeSeriesOnClause onClause, MakeSeriesRangeClause rangeClause, MakeSeriesByClause byClause) { this(makeSeriesKeyword, parameters, aggregates, onClause, rangeClause, byClause, null); }

    @Override public int childCount() { return 6; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return makeSeriesKeyword; case 1: return parameters; case 2: return aggregates; case 3: return onClause; case 4: return rangeClause; case 5: return byClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "MakeSeriesKeyword"; case 1: return "Parameters"; case 2: return "Aggregates"; case 3: return "OnClause"; case 4: return "RangeClause"; case 5: return "ByClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 5: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Aggregate; case 3: return CompletionHint.Clause; case 4: return CompletionHint.Clause; case 5: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMakeSeriesOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMakeSeriesOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MakeSeriesOperator(makeSeriesKeyword != null ? (SyntaxToken) makeSeriesKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            aggregates != null ? (SyntaxList1<SeparatedElement1<MakeSeriesExpression>>) aggregates.clone(includeDiagnostics) : null,
            onClause != null ? (MakeSeriesOnClause) onClause.clone(includeDiagnostics) : null,
            rangeClause != null ? (MakeSeriesRangeClause) rangeClause.clone(includeDiagnostics) : null,
            byClause != null ? (MakeSeriesByClause) byClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
