// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MaterializedViewCombineExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the Kusto syntax that represents the materilized-view-combine expression.
 */
public final class MaterializedViewCombineExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.MaterializedViewCombineExpression; }
    private final SyntaxToken materializedViewCombineKeyword;
    public SyntaxToken materializedViewCombineKeyword() { return materializedViewCombineKeyword; }
    private final MaterializedViewCombineNameClause viewName;
    public MaterializedViewCombineNameClause viewName() { return viewName; }
    private final MaterializedViewCombineClause baseClause;
    public MaterializedViewCombineClause baseClause() { return baseClause; }
    private final MaterializedViewCombineClause deltaClause;
    public MaterializedViewCombineClause deltaClause() { return deltaClause; }
    private final MaterializedViewCombineClause aggregationsClause;
    public MaterializedViewCombineClause aggregationsClause() { return aggregationsClause; }

    /** Constructs a new instance of {@link MaterializedViewCombineExpression}. */
    public MaterializedViewCombineExpression(SyntaxToken materializedViewCombineKeyword, MaterializedViewCombineNameClause viewName, MaterializedViewCombineClause baseClause, MaterializedViewCombineClause deltaClause, MaterializedViewCombineClause aggregationsClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.materializedViewCombineKeyword = attach(materializedViewCombineKeyword);
        this.viewName = attach(viewName);
        this.baseClause = attach(baseClause);
        this.deltaClause = attach(deltaClause);
        this.aggregationsClause = attach(aggregationsClause);
        this.init();
    }
    public MaterializedViewCombineExpression(SyntaxToken materializedViewCombineKeyword, MaterializedViewCombineNameClause viewName, MaterializedViewCombineClause baseClause, MaterializedViewCombineClause deltaClause, MaterializedViewCombineClause aggregationsClause) { this(materializedViewCombineKeyword, viewName, baseClause, deltaClause, aggregationsClause, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return materializedViewCombineKeyword; case 1: return viewName; case 2: return baseClause; case 3: return deltaClause; case 4: return aggregationsClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "MaterializedViewCombineKeyword"; case 1: return "ViewName"; case 2: return "BaseClause"; case 3: return "DeltaClause"; case 4: return "AggregationsClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMaterializedViewCombineExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMaterializedViewCombineExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MaterializedViewCombineExpression(materializedViewCombineKeyword != null ? (SyntaxToken) materializedViewCombineKeyword.clone(includeDiagnostics) : null,
            viewName != null ? (MaterializedViewCombineNameClause) viewName.clone(includeDiagnostics) : null,
            baseClause != null ? (MaterializedViewCombineClause) baseClause.clone(includeDiagnostics) : null,
            deltaClause != null ? (MaterializedViewCombineClause) deltaClause.clone(includeDiagnostics) : null,
            aggregationsClause != null ? (MaterializedViewCombineClause) aggregationsClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
