// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MvApplyOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MvApplyOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.MvApplyOperator; }
    private final SyntaxToken mvApplyKeyword;
    public SyntaxToken mvApplyKeyword() { return mvApplyKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<MvApplyExpression>> expressions;
    public SyntaxList1<SeparatedElement1<MvApplyExpression>> expressions() { return expressions; }
    private final MvApplyRowLimitClause rowLimitClause;
    public MvApplyRowLimitClause rowLimitClause() { return rowLimitClause; }
    private final MvApplyContextIdClause contextIdClause;
    public MvApplyContextIdClause contextIdClause() { return contextIdClause; }
    private final SyntaxToken onKeyword;
    public SyntaxToken onKeyword() { return onKeyword; }
    private final MvApplySubqueryExpression subquery;
    public MvApplySubqueryExpression subquery() { return subquery; }

    /** Constructs a new instance of {@link MvApplyOperator}. */
    public MvApplyOperator(SyntaxToken mvApplyKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MvApplyExpression>> expressions, MvApplyRowLimitClause rowLimitClause, MvApplyContextIdClause contextIdClause, SyntaxToken onKeyword, MvApplySubqueryExpression subquery, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.mvApplyKeyword = attach(mvApplyKeyword);
        this.parameters = attach(parameters);
        this.expressions = attach(expressions);
        this.rowLimitClause = attach(rowLimitClause, true);
        this.contextIdClause = attach(contextIdClause, true);
        this.onKeyword = attach(onKeyword);
        this.subquery = attach(subquery);
        this.init();
    }
    public MvApplyOperator(SyntaxToken mvApplyKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MvApplyExpression>> expressions, MvApplyRowLimitClause rowLimitClause, MvApplyContextIdClause contextIdClause, SyntaxToken onKeyword, MvApplySubqueryExpression subquery) { this(mvApplyKeyword, parameters, expressions, rowLimitClause, contextIdClause, onKeyword, subquery, null); }

    @Override public int childCount() { return 7; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return mvApplyKeyword; case 1: return parameters; case 2: return expressions; case 3: return rowLimitClause; case 4: return contextIdClause; case 5: return onKeyword; case 6: return subquery; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "MvApplyKeyword"; case 1: return "Parameters"; case 2: return "Expressions"; case 3: return "RowLimitClause"; case 4: return "ContextIdClause"; case 5: return "OnKeyword"; case 6: return "Subquery"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Scalar; case 3: return CompletionHint.Clause; case 4: return CompletionHint.Clause; case 5: return CompletionHint.Keyword; case 6: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMvApplyOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMvApplyOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MvApplyOperator(mvApplyKeyword != null ? (SyntaxToken) mvApplyKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<MvApplyExpression>>) expressions.clone(includeDiagnostics) : null,
            rowLimitClause != null ? (MvApplyRowLimitClause) rowLimitClause.clone(includeDiagnostics) : null,
            contextIdClause != null ? (MvApplyContextIdClause) contextIdClause.clone(includeDiagnostics) : null,
            onKeyword != null ? (SyntaxToken) onKeyword.clone(includeDiagnostics) : null,
            subquery != null ? (MvApplySubqueryExpression) subquery.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
