// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MvApplySubqueryExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MvApplySubqueryExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.MvApplySubqueryExpression; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link MvApplySubqueryExpression}. */
    public MvApplySubqueryExpression(SyntaxToken openParen, Expression expression, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openParen = attach(openParen);
        this.expression = attach(expression);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public MvApplySubqueryExpression(SyntaxToken openParen, Expression expression, SyntaxToken closeParen) { this(openParen, expression, closeParen, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openParen; case 1: return expression; case 2: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenParen"; case 1: return "Expression"; case 2: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Query; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMvApplySubqueryExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMvApplySubqueryExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MvApplySubqueryExpression(openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
