// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MvApplyExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MvApplyExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.MvApplyExpression; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final ToTypeOfClause toTypeOf;
    public ToTypeOfClause toTypeOf() { return toTypeOf; }

    /** Constructs a new instance of {@link MvApplyExpression}. */
    public MvApplyExpression(Expression expression, ToTypeOfClause toTypeOf, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.expression = attach(expression, true);
        this.toTypeOf = attach(toTypeOf, true);
        this.init();
    }
    public MvApplyExpression(Expression expression, ToTypeOfClause toTypeOf) { this(expression, toTypeOf, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return expression; case 1: return toTypeOf; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Expression"; case 1: return "ToTypeOf"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 0: case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Scalar; case 1: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMvApplyExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMvApplyExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MvApplyExpression(expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            toTypeOf != null ? (ToTypeOfClause) toTypeOf.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
