// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MvExpandOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MvExpandOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.MvExpandOperator; }
    private final SyntaxToken mvExpandKeyword;
    public SyntaxToken mvExpandKeyword() { return mvExpandKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<MvExpandExpression>> expressions;
    public SyntaxList1<SeparatedElement1<MvExpandExpression>> expressions() { return expressions; }
    private final MvExpandRowLimitClause rowLimitClause;
    public MvExpandRowLimitClause rowLimitClause() { return rowLimitClause; }

    /** Constructs a new instance of {@link MvExpandOperator}. */
    public MvExpandOperator(SyntaxToken mvExpandKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MvExpandExpression>> expressions, MvExpandRowLimitClause rowLimitClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.mvExpandKeyword = attach(mvExpandKeyword);
        this.parameters = attach(parameters);
        this.expressions = attach(expressions);
        this.rowLimitClause = attach(rowLimitClause, true);
        this.init();
    }
    public MvExpandOperator(SyntaxToken mvExpandKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<MvExpandExpression>> expressions, MvExpandRowLimitClause rowLimitClause) { this(mvExpandKeyword, parameters, expressions, rowLimitClause, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return mvExpandKeyword; case 1: return parameters; case 2: return expressions; case 3: return rowLimitClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "MvExpandKeyword"; case 1: return "Parameters"; case 2: return "Expressions"; case 3: return "RowLimitClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Scalar; case 3: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMvExpandOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMvExpandOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MvExpandOperator(mvExpandKeyword != null ? (SyntaxToken) mvExpandKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<MvExpandExpression>>) expressions.clone(includeDiagnostics) : null,
            rowLimitClause != null ? (MvExpandRowLimitClause) rowLimitClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
