// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node MvExpandRowLimitClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class MvExpandRowLimitClause extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.MvExpandRowLimitClause; }
    private final SyntaxToken limitKeyword;
    public SyntaxToken limitKeyword() { return limitKeyword; }
    private final Expression rowLimit;
    public Expression rowLimit() { return rowLimit; }

    /** Constructs a new instance of {@link MvExpandRowLimitClause}. */
    public MvExpandRowLimitClause(SyntaxToken limitKeyword, Expression rowLimit, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.limitKeyword = attach(limitKeyword);
        this.rowLimit = attach(rowLimit);
        this.init();
    }
    public MvExpandRowLimitClause(SyntaxToken limitKeyword, Expression rowLimit) { this(limitKeyword, rowLimit, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return limitKeyword; case 1: return rowLimit; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "LimitKeyword"; case 1: return "RowLimit"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitMvExpandRowLimitClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitMvExpandRowLimitClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new MvExpandRowLimitClause(limitKeyword != null ? (SyntaxToken) limitKeyword.clone(includeDiagnostics) : null,
            rowLimit != null ? (Expression) rowLimit.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
