// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node NamedParameter)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

public final class NamedParameter extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.NamedParameter; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final int expressionHint;
    public int expressionHint() { return expressionHint; }

    /** Constructs a new instance of {@link NamedParameter}. */
    public NamedParameter(NameDeclaration name, SyntaxToken equalToken, Expression expression, int expressionHint, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.name = attach(name);
        this.equalToken = attach(equalToken);
        this.expression = attach(expression);
        this.expressionHint = expressionHint;
        this.init();
    }
    public NamedParameter(NameDeclaration name, SyntaxToken equalToken, Expression expression, int expressionHint) { this(name, equalToken, expression, expressionHint, null); }
    public NamedParameter(NameDeclaration name, SyntaxToken equalToken, Expression expression) { this(name, equalToken, expression, CompletionHint.None, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return name; case 1: return equalToken; case 2: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Name"; case 1: return "EqualToken"; case 2: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Declaration; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitNamedParameter(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitNamedParameter(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new NamedParameter(name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            expressionHint,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:247-260">
    @Override
    public int getCompletionHint(int index) // PORT: §3.17 CompletionHint is an int holder (D23)
    {
        if (index == 2)
        {
            return this.expressionHint();
        }
        else
        {
            return super.getCompletionHint(index);
        }
    }
    // </hand-written>
}
