// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node NameDeclaration)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

// <hand-written-imports>
import java.util.List;
import org.graylog.kusto.language.Diagnostic;
// </hand-written-imports>

/**
 * A node in the Kusto syntax that represents a name declaration.
 */
public final class NameDeclaration extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.NameDeclaration; }
    private final Name name;
    /** The table name */
    public Name name() { return name; }

    /** Constructs a new instance of {@link NameDeclaration}. */
    public NameDeclaration(Name name, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.name = attach(name);
        this.init();
    }
    public NameDeclaration(Name name) { this(name, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return name; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Name"; default: throw new IndexOutOfBoundsException(); } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitNameDeclaration(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitNameDeclaration(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new NameDeclaration(name != null ? (Name) name.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:192-200">
    public String simpleName() { return this.name().simpleName(); }

    public NameDeclaration(SyntaxToken nameToken, List<Diagnostic> diagnostics)
    {
        this(new TokenName(nameToken), diagnostics);
    }

    public NameDeclaration(SyntaxToken nameToken) // PORT: §3.12
    {
        this(nameToken, null);
    }
    // </hand-written>
}
