// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node NameReferenceList)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

public final class NameReferenceList extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.NameReferenceList; }
    private final SyntaxList1<SeparatedElement1<NameReference>> names;
    public SyntaxList1<SeparatedElement1<NameReference>> names() { return names; }

    /** Constructs a new instance of {@link NameReferenceList}. */
    public NameReferenceList(SyntaxList1<SeparatedElement1<NameReference>> names, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.names = attach(names);
        this.init();
    }
    public NameReferenceList(SyntaxList1<SeparatedElement1<NameReference>> names) { this(names, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return names; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Names"; default: throw new IndexOutOfBoundsException(); } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitNameReferenceList(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitNameReferenceList(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new NameReferenceList(names != null ? (SyntaxList1<SeparatedElement1<NameReference>>) names.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
