// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node OrderingClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class OrderingClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.OrderingClause; }
    private final SyntaxToken ascOrDescKeyword;
    public SyntaxToken ascOrDescKeyword() { return ascOrDescKeyword; }
    private final OrderingNullsClause nullsClause;
    public OrderingNullsClause nullsClause() { return nullsClause; }

    /** Constructs a new instance of {@link OrderingClause}. */
    public OrderingClause(SyntaxToken ascOrDescKeyword, OrderingNullsClause nullsClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.ascOrDescKeyword = attach(ascOrDescKeyword, true);
        this.nullsClause = attach(nullsClause, true);
        this.init();
    }
    public OrderingClause(SyntaxToken ascOrDescKeyword, OrderingNullsClause nullsClause) { this(ascOrDescKeyword, nullsClause, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return ascOrDescKeyword; case 1: return nullsClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "AscOrDescKeyword"; case 1: return "NullsClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 0: case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitOrderingClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitOrderingClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new OrderingClause(ascOrDescKeyword != null ? (SyntaxToken) ascOrDescKeyword.clone(includeDiagnostics) : null,
            nullsClause != null ? (OrderingNullsClause) nullsClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
