// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PackExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PackExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.PackExpression; }
    private final SyntaxToken packKeyword;
    public SyntaxToken packKeyword() { return packKeyword; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxToken asteriskToken;
    public SyntaxToken asteriskToken() { return asteriskToken; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link PackExpression}. */
    public PackExpression(SyntaxToken packKeyword, SyntaxToken openParen, SyntaxToken asteriskToken, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.packKeyword = attach(packKeyword);
        this.openParen = attach(openParen);
        this.asteriskToken = attach(asteriskToken);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public PackExpression(SyntaxToken packKeyword, SyntaxToken openParen, SyntaxToken asteriskToken, SyntaxToken closeParen) { this(packKeyword, openParen, asteriskToken, closeParen, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return packKeyword; case 1: return openParen; case 2: return asteriskToken; case 3: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PackKeyword"; case 1: return "OpenParen"; case 2: return "AsteriskToken"; case 3: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPackExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPackExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PackExpression(packKeyword != null ? (SyntaxToken) packKeyword.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            asteriskToken != null ? (SyntaxToken) asteriskToken.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
