// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ParseKvOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ParseKvOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ParseKvOperator; }
    private final SyntaxToken parseKvKeyword;
    public SyntaxToken parseKvKeyword() { return parseKvKeyword; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken asKeyword;
    public SyntaxToken asKeyword() { return asKeyword; }
    private final RowSchema keys;
    public RowSchema keys() { return keys; }
    private final ParseKvWithClause withClause;
    public ParseKvWithClause withClause() { return withClause; }

    /** Constructs a new instance of {@link ParseKvOperator}. */
    public ParseKvOperator(SyntaxToken parseKvKeyword, Expression expression, SyntaxToken asKeyword, RowSchema keys, ParseKvWithClause withClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.parseKvKeyword = attach(parseKvKeyword);
        this.expression = attach(expression);
        this.asKeyword = attach(asKeyword);
        this.keys = attach(keys);
        this.withClause = attach(withClause, true);
        this.init();
    }
    public ParseKvOperator(SyntaxToken parseKvKeyword, Expression expression, SyntaxToken asKeyword, RowSchema keys, ParseKvWithClause withClause) { this(parseKvKeyword, expression, asKeyword, keys, withClause, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return parseKvKeyword; case 1: return expression; case 2: return asKeyword; case 3: return keys; case 4: return withClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ParseKvKeyword"; case 1: return "Expression"; case 2: return "AsKeyword"; case 3: return "Keys"; case 4: return "WithClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; case 2: return CompletionHint.Keyword; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitParseKvOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitParseKvOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ParseKvOperator(parseKvKeyword != null ? (SyntaxToken) parseKvKeyword.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            asKeyword != null ? (SyntaxToken) asKeyword.clone(includeDiagnostics) : null,
            keys != null ? (RowSchema) keys.clone(includeDiagnostics) : null,
            withClause != null ? (ParseKvWithClause) withClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
