// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PartitionByOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PartitionByOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.PartitionByOperator; }
    private final SyntaxToken partitionByKeyword;
    public SyntaxToken partitionByKeyword() { return partitionByKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final Expression entity;
    public Expression entity() { return entity; }
    private final PartitionByIdClause idClause;
    public PartitionByIdClause idClause() { return idClause; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final Expression subquery;
    public Expression subquery() { return subquery; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link PartitionByOperator}. */
    public PartitionByOperator(SyntaxToken partitionByKeyword, SyntaxList1<NamedParameter> parameters, Expression entity, PartitionByIdClause idClause, SyntaxToken openParen, Expression subquery, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.partitionByKeyword = attach(partitionByKeyword);
        this.parameters = attach(parameters);
        this.entity = attach(entity);
        this.idClause = attach(idClause, true);
        this.openParen = attach(openParen);
        this.subquery = attach(subquery);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public PartitionByOperator(SyntaxToken partitionByKeyword, SyntaxList1<NamedParameter> parameters, Expression entity, PartitionByIdClause idClause, SyntaxToken openParen, Expression subquery, SyntaxToken closeParen) { this(partitionByKeyword, parameters, entity, idClause, openParen, subquery, closeParen, null); }

    @Override public int childCount() { return 7; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return partitionByKeyword; case 1: return parameters; case 2: return entity; case 3: return idClause; case 4: return openParen; case 5: return subquery; case 6: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PartitionByKeyword"; case 1: return "Parameters"; case 2: return "Entity"; case 3: return "IdClause"; case 4: return "OpenParen"; case 5: return "Subquery"; case 6: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Column; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; case 5: return CompletionHint.Query; case 6: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPartitionByOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPartitionByOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PartitionByOperator(partitionByKeyword != null ? (SyntaxToken) partitionByKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            entity != null ? (Expression) entity.clone(includeDiagnostics) : null,
            idClause != null ? (PartitionByIdClause) idClause.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            subquery != null ? (Expression) subquery.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
