// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PartitionScope)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PartitionScope extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.PartitionScope; }
    private final SyntaxToken inKeyword;
    public SyntaxToken inKeyword() { return inKeyword; }
    private final Expression expression;
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link PartitionScope}. */
    public PartitionScope(SyntaxToken inKeyword, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.inKeyword = attach(inKeyword);
        this.expression = attach(expression);
        this.init();
    }
    public PartitionScope(SyntaxToken inKeyword, Expression expression) { this(inKeyword, expression, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return inKeyword; case 1: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "InKeyword"; case 1: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPartitionScope(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPartitionScope(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PartitionScope(inKeyword != null ? (SyntaxToken) inKeyword.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
