// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PatternPathParameter)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PatternPathParameter extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.PatternPathParameter; }
    private final SyntaxToken openBracket;
    public SyntaxToken openBracket() { return openBracket; }
    private final NameAndTypeDeclaration parameter;
    public NameAndTypeDeclaration parameter() { return parameter; }
    private final SyntaxToken closeBracket;
    public SyntaxToken closeBracket() { return closeBracket; }

    /** Constructs a new instance of {@link PatternPathParameter}. */
    public PatternPathParameter(SyntaxToken openBracket, NameAndTypeDeclaration parameter, SyntaxToken closeBracket, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.openBracket = attach(openBracket);
        this.parameter = attach(parameter);
        this.closeBracket = attach(closeBracket);
        this.init();
    }
    public PatternPathParameter(SyntaxToken openBracket, NameAndTypeDeclaration parameter, SyntaxToken closeBracket) { this(openBracket, parameter, closeBracket, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return openBracket; case 1: return parameter; case 2: return closeBracket; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OpenBracket"; case 1: return "Parameter"; case 2: return "CloseBracket"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPatternPathParameter(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPatternPathParameter(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PatternPathParameter(openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            parameter != null ? (NameAndTypeDeclaration) parameter.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
