// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PatternDeclaration)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PatternDeclaration extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.PatternDeclaration; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> parameters;
    public SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> parameters() { return parameters; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }
    private final PatternPathParameter pathParameter;
    public PatternPathParameter pathParameter() { return pathParameter; }
    private final SyntaxToken openBrace;
    public SyntaxToken openBrace() { return openBrace; }
    private final SyntaxList1<PatternMatch> patterns;
    public SyntaxList1<PatternMatch> patterns() { return patterns; }
    private final SyntaxToken closeBrace;
    public SyntaxToken closeBrace() { return closeBrace; }

    /** Constructs a new instance of {@link PatternDeclaration}. */
    public PatternDeclaration(SyntaxToken equalToken, SyntaxToken openParen, SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> parameters, SyntaxToken closeParen, PatternPathParameter pathParameter, SyntaxToken openBrace, SyntaxList1<PatternMatch> patterns, SyntaxToken closeBrace, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.equalToken = attach(equalToken);
        this.openParen = attach(openParen);
        this.parameters = attach(parameters);
        this.closeParen = attach(closeParen);
        this.pathParameter = attach(pathParameter, true);
        this.openBrace = attach(openBrace);
        this.patterns = attach(patterns);
        this.closeBrace = attach(closeBrace);
        this.init();
    }
    public PatternDeclaration(SyntaxToken equalToken, SyntaxToken openParen, SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>> parameters, SyntaxToken closeParen, PatternPathParameter pathParameter, SyntaxToken openBrace, SyntaxList1<PatternMatch> patterns, SyntaxToken closeBrace) { this(equalToken, openParen, parameters, closeParen, pathParameter, openBrace, patterns, closeBrace, null); }

    @Override public int childCount() { return 8; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return equalToken; case 1: return openParen; case 2: return parameters; case 3: return closeParen; case 4: return pathParameter; case 5: return openBrace; case 6: return patterns; case 7: return closeBrace; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "EqualToken"; case 1: return "OpenParen"; case 2: return "Parameters"; case 3: return "CloseParen"; case 4: return "PathParameter"; case 5: return "OpenBrace"; case 6: return "Patterns"; case 7: return "CloseBrace"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Clause; case 5: return CompletionHint.Syntax; case 6: return CompletionHint.Clause; case 7: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPatternDeclaration(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPatternDeclaration(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PatternDeclaration(equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<SeparatedElement1<NameAndTypeDeclaration>>) parameters.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            pathParameter != null ? (PatternPathParameter) pathParameter.clone(includeDiagnostics) : null,
            openBrace != null ? (SyntaxToken) openBrace.clone(includeDiagnostics) : null,
            patterns != null ? (SyntaxList1<PatternMatch>) patterns.clone(includeDiagnostics) : null,
            closeBrace != null ? (SyntaxToken) closeBrace.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
