// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PatternPathValue)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PatternPathValue extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.PatternPathValue; }
    private final SyntaxToken dotToken;
    public SyntaxToken dotToken() { return dotToken; }
    private final SyntaxToken openBracket;
    public SyntaxToken openBracket() { return openBracket; }
    private final Expression value;
    public Expression value() { return value; }
    private final SyntaxToken closeBracket;
    public SyntaxToken closeBracket() { return closeBracket; }

    /** Constructs a new instance of {@link PatternPathValue}. */
    public PatternPathValue(SyntaxToken dotToken, SyntaxToken openBracket, Expression value, SyntaxToken closeBracket, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.dotToken = attach(dotToken);
        this.openBracket = attach(openBracket);
        this.value = attach(value);
        this.closeBracket = attach(closeBracket);
        this.init();
    }
    public PatternPathValue(SyntaxToken dotToken, SyntaxToken openBracket, Expression value, SyntaxToken closeBracket) { this(dotToken, openBracket, value, closeBracket, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return dotToken; case 1: return openBracket; case 2: return value; case 3: return closeBracket; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "DotToken"; case 1: return "OpenBracket"; case 2: return "Value"; case 3: return "CloseBracket"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Scalar; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPatternPathValue(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPatternPathValue(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PatternPathValue(dotToken != null ? (SyntaxToken) dotToken.clone(includeDiagnostics) : null,
            openBracket != null ? (SyntaxToken) openBracket.clone(includeDiagnostics) : null,
            value != null ? (Expression) value.clone(includeDiagnostics) : null,
            closeBracket != null ? (SyntaxToken) closeBracket.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
