// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PrefixUnaryExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a prefix unary expression.
 */
public final class PrefixUnaryExpression extends Expression {
    private final SyntaxKind kind;
    @Override public SyntaxKind kind() { return this.kind; }
    private final SyntaxToken operator;
    /** The operator token. */
    public SyntaxToken operator() { return operator; }
    private final Expression expression;
    /** The expression. */
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link PrefixUnaryExpression}. */
    public PrefixUnaryExpression(SyntaxKind kind, SyntaxToken operator, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.kind = kind;
        this.operator = attach(operator);
        this.expression = attach(expression);
        this.init();
    }
    public PrefixUnaryExpression(SyntaxKind kind, SyntaxToken operator, Expression expression) { this(kind, operator, expression, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return operator; case 1: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Operator"; case 1: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPrefixUnaryExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPrefixUnaryExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PrefixUnaryExpression(this.kind(), operator != null ? (SyntaxToken) operator.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
