// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PrimitiveTypeExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PrimitiveTypeExpression extends TypeExpression {
    @Override public SyntaxKind kind() { return SyntaxKind.PrimitiveTypeExpression; }
    private final SyntaxToken type;
    public SyntaxToken type() { return type; }

    /** Constructs a new instance of {@link PrimitiveTypeExpression}. */
    public PrimitiveTypeExpression(SyntaxToken type, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.type = attach(type);
        this.init();
    }
    public PrimitiveTypeExpression(SyntaxToken type) { this(type, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return type; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Type"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPrimitiveTypeExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPrimitiveTypeExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PrimitiveTypeExpression(type != null ? (SyntaxToken) type.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
