// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node PrintOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class PrintOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.PrintOperator; }
    private final SyntaxToken printKeyword;
    public SyntaxToken printKeyword() { return printKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }

    /** Constructs a new instance of {@link PrintOperator}. */
    public PrintOperator(SyntaxToken printKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.printKeyword = attach(printKeyword);
        this.expressions = attach(expressions);
        this.init();
    }
    public PrintOperator(SyntaxToken printKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions) { this(printKeyword, expressions, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return printKeyword; case 1: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PrintKeyword"; case 1: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitPrintOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitPrintOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new PrintOperator(printKeyword != null ? (SyntaxToken) printKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
