// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ProjectAwayOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ProjectAwayOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ProjectAwayOperator; }
    private final SyntaxToken projectAwayKeyword;
    public SyntaxToken projectAwayKeyword() { return projectAwayKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }

    /** Constructs a new instance of {@link ProjectAwayOperator}. */
    public ProjectAwayOperator(SyntaxToken projectAwayKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.projectAwayKeyword = attach(projectAwayKeyword);
        this.expressions = attach(expressions);
        this.init();
    }
    public ProjectAwayOperator(SyntaxToken projectAwayKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions) { this(projectAwayKeyword, expressions, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return projectAwayKeyword; case 1: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ProjectAwayKeyword"; case 1: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitProjectAwayOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitProjectAwayOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ProjectAwayOperator(projectAwayKeyword != null ? (SyntaxToken) projectAwayKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
