// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node QueryBlock)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class QueryBlock extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.QueryBlock; }
    private final SyntaxList1<Directive> directives;
    public SyntaxList1<Directive> directives() { return directives; }
    private final SyntaxList1<SeparatedElement1<Statement>> statements;
    public SyntaxList1<SeparatedElement1<Statement>> statements() { return statements; }
    private final SkippedTokens skippedTokens;
    public SkippedTokens skippedTokens() { return skippedTokens; }
    private final SyntaxToken endOfQuery;
    public SyntaxToken endOfQuery() { return endOfQuery; }

    /** Constructs a new instance of {@link QueryBlock}. */
    public QueryBlock(SyntaxList1<Directive> directives, SyntaxList1<SeparatedElement1<Statement>> statements, SkippedTokens skippedTokens, SyntaxToken endOfQuery, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.directives = attach(directives);
        this.statements = attach(statements);
        this.skippedTokens = attach(skippedTokens, true);
        this.endOfQuery = attach(endOfQuery, true);
        this.init();
    }
    public QueryBlock(SyntaxList1<Directive> directives, SyntaxList1<SeparatedElement1<Statement>> statements, SkippedTokens skippedTokens, SyntaxToken endOfQuery) { this(directives, statements, skippedTokens, endOfQuery, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return directives; case 1: return statements; case 2: return skippedTokens; case 3: return endOfQuery; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Directives"; case 1: return "Statements"; case 2: return "SkippedTokens"; case 3: return "EndOfQuery"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 2: case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.None; case 1: return CompletionHint.NonScalar; case 2: return CompletionHint.None; case 3: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitQueryBlock(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitQueryBlock(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new QueryBlock(directives != null ? (SyntaxList1<Directive>) directives.clone(includeDiagnostics) : null,
            statements != null ? (SyntaxList1<SeparatedElement1<Statement>>) statements.clone(includeDiagnostics) : null,
            skippedTokens != null ? (SkippedTokens) skippedTokens.clone(includeDiagnostics) : null,
            endOfQuery != null ? (SyntaxToken) endOfQuery.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
