// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node RangeOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class RangeOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.RangeOperator; }
    private final SyntaxToken rangeToken;
    public SyntaxToken rangeToken() { return rangeToken; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final SyntaxToken fromToken;
    public SyntaxToken fromToken() { return fromToken; }
    private final Expression from;
    public Expression from() { return from; }
    private final SyntaxToken toToken;
    public SyntaxToken toToken() { return toToken; }
    private final Expression to;
    public Expression to() { return to; }
    private final SyntaxToken stepToken;
    public SyntaxToken stepToken() { return stepToken; }
    private final Expression step;
    public Expression step() { return step; }

    /** Constructs a new instance of {@link RangeOperator}. */
    public RangeOperator(SyntaxToken rangeToken, NameDeclaration name, SyntaxToken fromToken, Expression from, SyntaxToken toToken, Expression to, SyntaxToken stepToken, Expression step, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.rangeToken = attach(rangeToken);
        this.name = attach(name);
        this.fromToken = attach(fromToken);
        this.from = attach(from);
        this.toToken = attach(toToken);
        this.to = attach(to);
        this.stepToken = attach(stepToken);
        this.step = attach(step);
        this.init();
    }
    public RangeOperator(SyntaxToken rangeToken, NameDeclaration name, SyntaxToken fromToken, Expression from, SyntaxToken toToken, Expression to, SyntaxToken stepToken, Expression step) { this(rangeToken, name, fromToken, from, toToken, to, stepToken, step, null); }

    @Override public int childCount() { return 8; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return rangeToken; case 1: return name; case 2: return fromToken; case 3: return from; case 4: return toToken; case 5: return to; case 6: return stepToken; case 7: return step; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "RangeToken"; case 1: return "Name"; case 2: return "FromToken"; case 3: return "From"; case 4: return "ToToken"; case 5: return "To"; case 6: return "StepToken"; case 7: return "Step"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Declaration; case 2: return CompletionHint.Keyword; case 3: return CompletionHint.Scalar; case 4: return CompletionHint.Keyword; case 5: return CompletionHint.Scalar; case 6: return CompletionHint.Keyword; case 7: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitRangeOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitRangeOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new RangeOperator(rangeToken != null ? (SyntaxToken) rangeToken.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            fromToken != null ? (SyntaxToken) fromToken.clone(includeDiagnostics) : null,
            from != null ? (Expression) from.clone(includeDiagnostics) : null,
            toToken != null ? (SyntaxToken) toToken.clone(includeDiagnostics) : null,
            to != null ? (Expression) to.clone(includeDiagnostics) : null,
            stepToken != null ? (SyntaxToken) stepToken.clone(includeDiagnostics) : null,
            step != null ? (Expression) step.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
