// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ReduceByOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ReduceByOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ReduceByOperator; }
    private final SyntaxToken reduceKeyword;
    public SyntaxToken reduceKeyword() { return reduceKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxToken byKeyword;
    public SyntaxToken byKeyword() { return byKeyword; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final ReduceByWithClause with;
    public ReduceByWithClause with() { return with; }

    /** Constructs a new instance of {@link ReduceByOperator}. */
    public ReduceByOperator(SyntaxToken reduceKeyword, SyntaxList1<NamedParameter> parameters, SyntaxToken byKeyword, Expression expression, ReduceByWithClause with, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.reduceKeyword = attach(reduceKeyword);
        this.parameters = attach(parameters);
        this.byKeyword = attach(byKeyword);
        this.expression = attach(expression);
        this.with = attach(with, true);
        this.init();
    }
    public ReduceByOperator(SyntaxToken reduceKeyword, SyntaxList1<NamedParameter> parameters, SyntaxToken byKeyword, Expression expression, ReduceByWithClause with) { this(reduceKeyword, parameters, byKeyword, expression, with, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return reduceKeyword; case 1: return parameters; case 2: return byKeyword; case 3: return expression; case 4: return with; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ReduceKeyword"; case 1: return "Parameters"; case 2: return "ByKeyword"; case 3: return "Expression"; case 4: return "With"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Keyword; case 3: return CompletionHint.Scalar; case 4: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitReduceByOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitReduceByOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ReduceByOperator(reduceKeyword != null ? (SyntaxToken) reduceKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            byKeyword != null ? (SyntaxToken) byKeyword.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            with != null ? (ReduceByWithClause) with.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
