// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node RenderOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class RenderOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.RenderOperator; }
    private final SyntaxToken renderKeyword;
    public SyntaxToken renderKeyword() { return renderKeyword; }
    private final SyntaxToken chartType;
    public SyntaxToken chartType() { return chartType; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final RenderWithClause withClause;
    public RenderWithClause withClause() { return withClause; }

    /** Constructs a new instance of {@link RenderOperator}. */
    public RenderOperator(SyntaxToken renderKeyword, SyntaxToken chartType, SyntaxList1<NamedParameter> parameters, RenderWithClause withClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.renderKeyword = attach(renderKeyword);
        this.chartType = attach(chartType, true);
        this.parameters = attach(parameters);
        this.withClause = attach(withClause, true);
        this.init();
    }
    public RenderOperator(SyntaxToken renderKeyword, SyntaxToken chartType, SyntaxList1<NamedParameter> parameters, RenderWithClause withClause) { this(renderKeyword, chartType, parameters, withClause, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return renderKeyword; case 1: return chartType; case 2: return parameters; case 3: return withClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "RenderKeyword"; case 1: return "ChartType"; case 2: return "Parameters"; case 3: return "WithClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Keyword; case 2: return CompletionHint.None; case 3: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitRenderOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitRenderOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new RenderOperator(renderKeyword != null ? (SyntaxToken) renderKeyword.clone(includeDiagnostics) : null,
            chartType != null ? (SyntaxToken) chartType.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            withClause != null ? (RenderWithClause) withClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
