// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node RestrictStatementWithClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class RestrictStatementWithClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.RestrictStatementWithClause; }
    private final SyntaxToken withKeyword;
    public SyntaxToken withKeyword() { return withKeyword; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxList1<SeparatedElement1<NamedParameter>> properties;
    public SyntaxList1<SeparatedElement1<NamedParameter>> properties() { return properties; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link RestrictStatementWithClause}. */
    public RestrictStatementWithClause(SyntaxToken withKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<NamedParameter>> properties, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.withKeyword = attach(withKeyword);
        this.openParen = attach(openParen);
        this.properties = attach(properties);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public RestrictStatementWithClause(SyntaxToken withKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<NamedParameter>> properties, SyntaxToken closeParen) { this(withKeyword, openParen, properties, closeParen, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return withKeyword; case 1: return openParen; case 2: return properties; case 3: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "WithKeyword"; case 1: return "OpenParen"; case 2: return "Properties"; case 3: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.None; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitRestrictStatementWithClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitRestrictStatementWithClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new RestrictStatementWithClause(withKeyword != null ? (SyntaxToken) withKeyword.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            properties != null ? (SyntaxList1<SeparatedElement1<NamedParameter>>) properties.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
