// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node SampleOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class SampleOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.SampleOperator; }
    private final SyntaxToken sampleKeyword;
    public SyntaxToken sampleKeyword() { return sampleKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final Expression expression;
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link SampleOperator}. */
    public SampleOperator(SyntaxToken sampleKeyword, SyntaxList1<NamedParameter> parameters, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.sampleKeyword = attach(sampleKeyword);
        this.parameters = attach(parameters);
        this.expression = attach(expression);
        this.init();
    }
    public SampleOperator(SyntaxToken sampleKeyword, SyntaxList1<NamedParameter> parameters, Expression expression) { this(sampleKeyword, parameters, expression, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return sampleKeyword; case 1: return parameters; case 2: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "SampleKeyword"; case 1: return "Parameters"; case 2: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Number; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitSampleOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitSampleOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new SampleOperator(sampleKeyword != null ? (SyntaxToken) sampleKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
