// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanDeclareClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanDeclareClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanDeclareClause; }
    private final SyntaxToken declareKeyword;
    public SyntaxToken declareKeyword() { return declareKeyword; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxList1<SeparatedElement1<FunctionParameter>> declarations;
    public SyntaxList1<SeparatedElement1<FunctionParameter>> declarations() { return declarations; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link ScanDeclareClause}. */
    public ScanDeclareClause(SyntaxToken declareKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<FunctionParameter>> declarations, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.declareKeyword = attach(declareKeyword);
        this.openParen = attach(openParen);
        this.declarations = attach(declarations);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public ScanDeclareClause(SyntaxToken declareKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<FunctionParameter>> declarations, SyntaxToken closeParen) { this(declareKeyword, openParen, declarations, closeParen, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return declareKeyword; case 1: return openParen; case 2: return declarations; case 3: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "DeclareKeyword"; case 1: return "OpenParen"; case 2: return "Declarations"; case 3: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanDeclareClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanDeclareClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanDeclareClause(declareKeyword != null ? (SyntaxToken) declareKeyword.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            declarations != null ? (SyntaxList1<SeparatedElement1<FunctionParameter>>) declarations.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
