// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanPartitionByClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanPartitionByClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanPartitionByClause; }
    private final SyntaxToken partitionKeyword;
    public SyntaxToken partitionKeyword() { return partitionKeyword; }
    private final SyntaxToken byKeyword;
    public SyntaxToken byKeyword() { return byKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }

    /** Constructs a new instance of {@link ScanPartitionByClause}. */
    public ScanPartitionByClause(SyntaxToken partitionKeyword, SyntaxToken byKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.partitionKeyword = attach(partitionKeyword);
        this.byKeyword = attach(byKeyword);
        this.expressions = attach(expressions);
        this.init();
    }
    public ScanPartitionByClause(SyntaxToken partitionKeyword, SyntaxToken byKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions) { this(partitionKeyword, byKeyword, expressions, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return partitionKeyword; case 1: return byKeyword; case 2: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "PartitionKeyword"; case 1: return "ByKeyword"; case 2: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Keyword; case 2: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanPartitionByClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanPartitionByClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanPartitionByClause(partitionKeyword != null ? (SyntaxToken) partitionKeyword.clone(includeDiagnostics) : null,
            byKeyword != null ? (SyntaxToken) byKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
