// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanStepOutput)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanStepOutput extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanStepOutput; }
    private final SyntaxToken outputKeyword;
    public SyntaxToken outputKeyword() { return outputKeyword; }
    private final SyntaxToken equalToken;
    public SyntaxToken equalToken() { return equalToken; }
    private final SyntaxToken outputKind;
    public SyntaxToken outputKind() { return outputKind; }

    /** Constructs a new instance of {@link ScanStepOutput}. */
    public ScanStepOutput(SyntaxToken outputKeyword, SyntaxToken equalToken, SyntaxToken outputKind, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.outputKeyword = attach(outputKeyword);
        this.equalToken = attach(equalToken);
        this.outputKind = attach(outputKind);
        this.init();
    }
    public ScanStepOutput(SyntaxToken outputKeyword, SyntaxToken equalToken, SyntaxToken outputKind) { this(outputKeyword, equalToken, outputKind, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return outputKeyword; case 1: return equalToken; case 2: return outputKind; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "OutputKeyword"; case 1: return "EqualToken"; case 2: return "OutputKind"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Keyword; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanStepOutput(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanStepOutput(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanStepOutput(outputKeyword != null ? (SyntaxToken) outputKeyword.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            outputKind != null ? (SyntaxToken) outputKind.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
