// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanComputationClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanComputationClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanComputationClause; }
    private final SyntaxToken arrowToken;
    public SyntaxToken arrowToken() { return arrowToken; }
    private final SyntaxList1<SeparatedElement1<ScanAssignment>> assignments;
    public SyntaxList1<SeparatedElement1<ScanAssignment>> assignments() { return assignments; }

    /** Constructs a new instance of {@link ScanComputationClause}. */
    public ScanComputationClause(SyntaxToken arrowToken, SyntaxList1<SeparatedElement1<ScanAssignment>> assignments, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.arrowToken = attach(arrowToken);
        this.assignments = attach(assignments);
        this.init();
    }
    public ScanComputationClause(SyntaxToken arrowToken, SyntaxList1<SeparatedElement1<ScanAssignment>> assignments) { this(arrowToken, assignments, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return arrowToken; case 1: return assignments; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ArrowToken"; case 1: return "Assignments"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; case 1: return CompletionHint.Column; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanComputationClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanComputationClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanComputationClause(arrowToken != null ? (SyntaxToken) arrowToken.clone(includeDiagnostics) : null,
            assignments != null ? (SyntaxList1<SeparatedElement1<ScanAssignment>>) assignments.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
