// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanStep)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanStep extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanStep; }
    private final SyntaxToken stepKeyword;
    public SyntaxToken stepKeyword() { return stepKeyword; }
    private final NameDeclaration name;
    public NameDeclaration name() { return name; }
    private final SyntaxToken optionalKeyword;
    public SyntaxToken optionalKeyword() { return optionalKeyword; }
    private final ScanStepOutput scanStepOutput;
    public ScanStepOutput scanStepOutput() { return scanStepOutput; }
    private final SyntaxToken colonToken;
    public SyntaxToken colonToken() { return colonToken; }
    private final Expression condition;
    public Expression condition() { return condition; }
    private final ScanComputationClause computationClause;
    public ScanComputationClause computationClause() { return computationClause; }
    private final SyntaxToken semicolonToken;
    public SyntaxToken semicolonToken() { return semicolonToken; }

    /** Constructs a new instance of {@link ScanStep}. */
    public ScanStep(SyntaxToken stepKeyword, NameDeclaration name, SyntaxToken optionalKeyword, ScanStepOutput scanStepOutput, SyntaxToken colonToken, Expression condition, ScanComputationClause computationClause, SyntaxToken semicolonToken, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.stepKeyword = attach(stepKeyword);
        this.name = attach(name);
        this.optionalKeyword = attach(optionalKeyword, true);
        this.scanStepOutput = attach(scanStepOutput, true);
        this.colonToken = attach(colonToken);
        this.condition = attach(condition);
        this.computationClause = attach(computationClause, true);
        this.semicolonToken = attach(semicolonToken);
        this.init();
    }
    public ScanStep(SyntaxToken stepKeyword, NameDeclaration name, SyntaxToken optionalKeyword, ScanStepOutput scanStepOutput, SyntaxToken colonToken, Expression condition, ScanComputationClause computationClause, SyntaxToken semicolonToken) { this(stepKeyword, name, optionalKeyword, scanStepOutput, colonToken, condition, computationClause, semicolonToken, null); }

    @Override public int childCount() { return 8; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return stepKeyword; case 1: return name; case 2: return optionalKeyword; case 3: return scanStepOutput; case 4: return colonToken; case 5: return condition; case 6: return computationClause; case 7: return semicolonToken; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "StepKeyword"; case 1: return "Name"; case 2: return "OptionalKeyword"; case 3: return "ScanStepOutput"; case 4: return "ColonToken"; case 5: return "Condition"; case 6: return "ComputationClause"; case 7: return "SemicolonToken"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 2: case 3: case 6: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Keyword; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; case 5: return CompletionHint.Scalar; case 6: return CompletionHint.Syntax; case 7: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanStep(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanStep(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanStep(stepKeyword != null ? (SyntaxToken) stepKeyword.clone(includeDiagnostics) : null,
            name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            optionalKeyword != null ? (SyntaxToken) optionalKeyword.clone(includeDiagnostics) : null,
            scanStepOutput != null ? (ScanStepOutput) scanStepOutput.clone(includeDiagnostics) : null,
            colonToken != null ? (SyntaxToken) colonToken.clone(includeDiagnostics) : null,
            condition != null ? (Expression) condition.clone(includeDiagnostics) : null,
            computationClause != null ? (ScanComputationClause) computationClause.clone(includeDiagnostics) : null,
            semicolonToken != null ? (SyntaxToken) semicolonToken.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
