// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ScanOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class ScanOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.ScanOperator; }
    private final SyntaxToken scanKeyword;
    public SyntaxToken scanKeyword() { return scanKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final ScanOrderByClause orderByClause;
    public ScanOrderByClause orderByClause() { return orderByClause; }
    private final ScanPartitionByClause partitionByClause;
    public ScanPartitionByClause partitionByClause() { return partitionByClause; }
    private final ScanDeclareClause declareClause;
    public ScanDeclareClause declareClause() { return declareClause; }
    private final SyntaxToken withKeyword;
    public SyntaxToken withKeyword() { return withKeyword; }
    private final SyntaxToken openParenToken;
    public SyntaxToken openParenToken() { return openParenToken; }
    private final SyntaxList1<ScanStep> steps;
    public SyntaxList1<ScanStep> steps() { return steps; }
    private final SyntaxToken closeParenToken;
    public SyntaxToken closeParenToken() { return closeParenToken; }

    /** Constructs a new instance of {@link ScanOperator}. */
    public ScanOperator(SyntaxToken scanKeyword, SyntaxList1<NamedParameter> parameters, ScanOrderByClause orderByClause, ScanPartitionByClause partitionByClause, ScanDeclareClause declareClause, SyntaxToken withKeyword, SyntaxToken openParenToken, SyntaxList1<ScanStep> steps, SyntaxToken closeParenToken, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.scanKeyword = attach(scanKeyword);
        this.parameters = attach(parameters);
        this.orderByClause = attach(orderByClause, true);
        this.partitionByClause = attach(partitionByClause, true);
        this.declareClause = attach(declareClause, true);
        this.withKeyword = attach(withKeyword);
        this.openParenToken = attach(openParenToken, true);
        this.steps = attach(steps);
        this.closeParenToken = attach(closeParenToken, true);
        this.init();
    }
    public ScanOperator(SyntaxToken scanKeyword, SyntaxList1<NamedParameter> parameters, ScanOrderByClause orderByClause, ScanPartitionByClause partitionByClause, ScanDeclareClause declareClause, SyntaxToken withKeyword, SyntaxToken openParenToken, SyntaxList1<ScanStep> steps, SyntaxToken closeParenToken) { this(scanKeyword, parameters, orderByClause, partitionByClause, declareClause, withKeyword, openParenToken, steps, closeParenToken, null); }

    @Override public int childCount() { return 9; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return scanKeyword; case 1: return parameters; case 2: return orderByClause; case 3: return partitionByClause; case 4: return declareClause; case 5: return withKeyword; case 6: return openParenToken; case 7: return steps; case 8: return closeParenToken; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ScanKeyword"; case 1: return "Parameters"; case 2: return "OrderByClause"; case 3: return "PartitionByClause"; case 4: return "DeclareClause"; case 5: return "WithKeyword"; case 6: return "OpenParenToken"; case 7: return "Steps"; case 8: return "CloseParenToken"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 2: case 3: case 4: case 6: case 8: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Syntax; case 4: return CompletionHint.Syntax; case 5: return CompletionHint.Keyword; case 6: return CompletionHint.Syntax; case 7: return CompletionHint.Syntax; case 8: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitScanOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitScanOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ScanOperator(scanKeyword != null ? (SyntaxToken) scanKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            orderByClause != null ? (ScanOrderByClause) orderByClause.clone(includeDiagnostics) : null,
            partitionByClause != null ? (ScanPartitionByClause) partitionByClause.clone(includeDiagnostics) : null,
            declareClause != null ? (ScanDeclareClause) declareClause.clone(includeDiagnostics) : null,
            withKeyword != null ? (SyntaxToken) withKeyword.clone(includeDiagnostics) : null,
            openParenToken != null ? (SyntaxToken) openParenToken.clone(includeDiagnostics) : null,
            steps != null ? (SyntaxList1<ScanStep>) steps.clone(includeDiagnostics) : null,
            closeParenToken != null ? (SyntaxToken) closeParenToken.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
