// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node SimpleNamedExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the kusto syntax that represents a named expression.
 */
public final class SimpleNamedExpression extends NamedExpression {
    @Override public SyntaxKind kind() { return SyntaxKind.SimpleNamedExpression; }
    private final NameDeclaration name;
    /** The name of the expression. */
    public NameDeclaration name() { return name; }
    private final SyntaxToken equalToken;
    /** The equal token. */
    public SyntaxToken equalToken() { return equalToken; }
    private final Expression expression;
    /** The named expression. */
    public Expression expression() { return expression; }

    /** Constructs a new instance of {@link SimpleNamedExpression}. */
    public SimpleNamedExpression(NameDeclaration name, SyntaxToken equalToken, Expression expression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.name = attach(name);
        this.equalToken = attach(equalToken);
        this.expression = attach(expression);
        this.init();
    }
    public SimpleNamedExpression(NameDeclaration name, SyntaxToken equalToken, Expression expression) { this(name, equalToken, expression, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return name; case 1: return equalToken; case 2: return expression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Name"; case 1: return "EqualToken"; case 2: return "Expression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Declaration; case 1: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitSimpleNamedExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitSimpleNamedExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new SimpleNamedExpression(name != null ? (NameDeclaration) name.clone(includeDiagnostics) : null,
            equalToken != null ? (SyntaxToken) equalToken.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
