// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node Statement)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;

/**
 * A node in the Kusto syntax that represents a statement.
 */
public abstract class Statement extends SyntaxNode {
    /** Constructs a new instance of {@link Statement}. */
    public Statement(List<Diagnostic> diagnostics) {
        super(diagnostics);
    }
    public Statement() { this(null); }
}
