// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node SummarizeOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class SummarizeOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.SummarizeOperator; }
    private final SyntaxToken summarizeKeyword;
    public SyntaxToken summarizeKeyword() { return summarizeKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<Expression>> aggregates;
    public SyntaxList1<SeparatedElement1<Expression>> aggregates() { return aggregates; }
    private final SummarizeByClause byClause;
    public SummarizeByClause byClause() { return byClause; }

    /** Constructs a new instance of {@link SummarizeOperator}. */
    public SummarizeOperator(SyntaxToken summarizeKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<Expression>> aggregates, SummarizeByClause byClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.summarizeKeyword = attach(summarizeKeyword);
        this.parameters = attach(parameters);
        this.aggregates = attach(aggregates);
        this.byClause = attach(byClause, true);
        this.init();
    }
    public SummarizeOperator(SyntaxToken summarizeKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<Expression>> aggregates, SummarizeByClause byClause) { this(summarizeKeyword, parameters, aggregates, byClause, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return summarizeKeyword; case 1: return parameters; case 2: return aggregates; case 3: return byClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "SummarizeKeyword"; case 1: return "Parameters"; case 2: return "Aggregates"; case 3: return "ByClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 3: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Aggregate; case 3: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitSummarizeOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitSummarizeOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new SummarizeOperator(summarizeKeyword != null ? (SyntaxToken) summarizeKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            aggregates != null ? (SyntaxList1<SeparatedElement1<Expression>>) aggregates.clone(includeDiagnostics) : null,
            byClause != null ? (SummarizeByClause) byClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
