// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node SummarizeByClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class SummarizeByClause extends Clause {
    @Override public SyntaxKind kind() { return SyntaxKind.SummarizeByClause; }
    private final SyntaxToken byKeyword;
    public SyntaxToken byKeyword() { return byKeyword; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }
    private final NamedExpression binClause;
    public NamedExpression binClause() { return binClause; }

    /** Constructs a new instance of {@link SummarizeByClause}. */
    public SummarizeByClause(SyntaxToken byKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, NamedExpression binClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.byKeyword = attach(byKeyword);
        this.expressions = attach(expressions);
        this.binClause = attach(binClause, true);
        this.init();
    }
    public SummarizeByClause(SyntaxToken byKeyword, SyntaxList1<SeparatedElement1<Expression>> expressions, NamedExpression binClause) { this(byKeyword, expressions, binClause, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return byKeyword; case 1: return expressions; case 2: return binClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ByKeyword"; case 1: return "Expressions"; case 2: return "BinClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 2: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Scalar; case 2: return CompletionHint.None; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitSummarizeByClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitSummarizeByClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new SummarizeByClause(byKeyword != null ? (SyntaxToken) byKeyword.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            binClause != null ? (NamedExpression) binClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
