// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node TopHittersOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class TopHittersOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.TopHittersOperator; }
    private final SyntaxToken topHittersKeyword;
    public SyntaxToken topHittersKeyword() { return topHittersKeyword; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken ofKeyword;
    public SyntaxToken ofKeyword() { return ofKeyword; }
    private final Expression ofExpression;
    public Expression ofExpression() { return ofExpression; }
    private final TopHittersByClause byClause;
    public TopHittersByClause byClause() { return byClause; }

    /** Constructs a new instance of {@link TopHittersOperator}. */
    public TopHittersOperator(SyntaxToken topHittersKeyword, Expression expression, SyntaxToken ofKeyword, Expression ofExpression, TopHittersByClause byClause, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.topHittersKeyword = attach(topHittersKeyword);
        this.expression = attach(expression);
        this.ofKeyword = attach(ofKeyword);
        this.ofExpression = attach(ofExpression);
        this.byClause = attach(byClause, true);
        this.init();
    }
    public TopHittersOperator(SyntaxToken topHittersKeyword, Expression expression, SyntaxToken ofKeyword, Expression ofExpression, TopHittersByClause byClause) { this(topHittersKeyword, expression, ofKeyword, ofExpression, byClause, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return topHittersKeyword; case 1: return expression; case 2: return ofKeyword; case 3: return ofExpression; case 4: return byClause; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "TopHittersKeyword"; case 1: return "Expression"; case 2: return "OfKeyword"; case 3: return "OfExpression"; case 4: return "ByClause"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 4: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Number; case 2: return CompletionHint.Keyword; case 3: return CompletionHint.Scalar; case 4: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitTopHittersOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitTopHittersOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new TopHittersOperator(topHittersKeyword != null ? (SyntaxToken) topHittersKeyword.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            ofKeyword != null ? (SyntaxToken) ofKeyword.clone(includeDiagnostics) : null,
            ofExpression != null ? (Expression) ofExpression.clone(includeDiagnostics) : null,
            byClause != null ? (TopHittersByClause) byClause.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
