// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node TopNestedOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class TopNestedOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.TopNestedOperator; }
    private final SyntaxList1<SeparatedElement1<TopNestedClause>> clauses;
    public SyntaxList1<SeparatedElement1<TopNestedClause>> clauses() { return clauses; }

    /** Constructs a new instance of {@link TopNestedOperator}. */
    public TopNestedOperator(SyntaxList1<SeparatedElement1<TopNestedClause>> clauses, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.clauses = attach(clauses);
        this.init();
    }
    public TopNestedOperator(SyntaxList1<SeparatedElement1<TopNestedClause>> clauses) { this(clauses, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return clauses; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Clauses"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Clause; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitTopNestedOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitTopNestedOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new TopNestedOperator(clauses != null ? (SyntaxList1<SeparatedElement1<TopNestedClause>>) clauses.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
