// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node TopOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class TopOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.TopOperator; }
    private final SyntaxToken topKeyword;
    public SyntaxToken topKeyword() { return topKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken byKeyword;
    public SyntaxToken byKeyword() { return byKeyword; }
    private final Expression byExpression;
    public Expression byExpression() { return byExpression; }

    /** Constructs a new instance of {@link TopOperator}. */
    public TopOperator(SyntaxToken topKeyword, SyntaxList1<NamedParameter> parameters, Expression expression, SyntaxToken byKeyword, Expression byExpression, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.topKeyword = attach(topKeyword);
        this.parameters = attach(parameters);
        this.expression = attach(expression);
        this.byKeyword = attach(byKeyword);
        this.byExpression = attach(byExpression);
        this.init();
    }
    public TopOperator(SyntaxToken topKeyword, SyntaxList1<NamedParameter> parameters, Expression expression, SyntaxToken byKeyword, Expression byExpression) { this(topKeyword, parameters, expression, byKeyword, byExpression, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return topKeyword; case 1: return parameters; case 2: return expression; case 3: return byKeyword; case 4: return byExpression; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "TopKeyword"; case 1: return "Parameters"; case 2: return "Expression"; case 3: return "ByKeyword"; case 4: return "ByExpression"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.Number; case 3: return CompletionHint.Keyword; case 4: return CompletionHint.Scalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitTopOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitTopOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new TopOperator(topKeyword != null ? (SyntaxToken) topKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            byKeyword != null ? (SyntaxToken) byKeyword.clone(includeDiagnostics) : null,
            byExpression != null ? (Expression) byExpression.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
