// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node ToTableExpression)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

/**
 * A node in the Kusto syntax that represents the totable operation.
 */
public final class ToTableExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.ToTableExpression; }
    private final SyntaxToken toTable;
    public SyntaxToken toTable() { return toTable; }
    private final NamedParameter kindParameter;
    public NamedParameter kindParameter() { return kindParameter; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final Expression expression;
    public Expression expression() { return expression; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link ToTableExpression}. */
    public ToTableExpression(SyntaxToken toTable, NamedParameter kindParameter, SyntaxToken openParen, Expression expression, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.toTable = attach(toTable);
        this.kindParameter = attach(kindParameter, true);
        this.openParen = attach(openParen);
        this.expression = attach(expression);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public ToTableExpression(SyntaxToken toTable, NamedParameter kindParameter, SyntaxToken openParen, Expression expression, SyntaxToken closeParen) { this(toTable, kindParameter, openParen, expression, closeParen, null); }

    @Override public int childCount() { return 5; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return toTable; case 1: return kindParameter; case 2: return openParen; case 3: return expression; case 4: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "ToTable"; case 1: return "KindParameter"; case 2: return "OpenParen"; case 3: return "Expression"; case 4: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override public boolean isOptional(int index) { switch (index) { case 1: return true; default: return false; } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 1: return CompletionHint.Clause; case 2: return CompletionHint.Syntax; case 3: return CompletionHint.Scalar; case 4: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitToTableExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitToTableExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new ToTableExpression(toTable != null ? (SyntaxToken) toTable.clone(includeDiagnostics) : null,
            kindParameter != null ? (NamedParameter) kindParameter.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            expression != null ? (Expression) expression.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
