// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node TypeOfLiteralExpression)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

/**
 * A node in the Kusto syntax that represents a typeof expression
 */
public final class TypeOfLiteralExpression extends Expression {
    @Override public SyntaxKind kind() { return SyntaxKind.TypeOfLiteralExpression; }
    private final SyntaxToken typeOfKeyword;
    public SyntaxToken typeOfKeyword() { return typeOfKeyword; }
    private final SyntaxToken openParen;
    public SyntaxToken openParen() { return openParen; }
    private final SyntaxList1<SeparatedElement1<Expression>> types;
    public SyntaxList1<SeparatedElement1<Expression>> types() { return types; }
    private final SyntaxToken closeParen;
    public SyntaxToken closeParen() { return closeParen; }

    /** Constructs a new instance of {@link TypeOfLiteralExpression}. */
    public TypeOfLiteralExpression(SyntaxToken typeOfKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<Expression>> types, SyntaxToken closeParen, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.typeOfKeyword = attach(typeOfKeyword);
        this.openParen = attach(openParen);
        this.types = attach(types);
        this.closeParen = attach(closeParen);
        this.init();
    }
    public TypeOfLiteralExpression(SyntaxToken typeOfKeyword, SyntaxToken openParen, SyntaxList1<SeparatedElement1<Expression>> types, SyntaxToken closeParen) { this(typeOfKeyword, openParen, types, closeParen, null); }

    @Override public int childCount() { return 4; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return typeOfKeyword; case 1: return openParen; case 2: return types; case 3: return closeParen; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "TypeOfKeyword"; case 1: return "OpenParen"; case 2: return "Types"; case 3: return "CloseParen"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.None; case 1: return CompletionHint.Syntax; case 2: return CompletionHint.Declaration; case 3: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitTypeOfLiteralExpression(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitTypeOfLiteralExpression(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new TypeOfLiteralExpression(typeOfKeyword != null ? (SyntaxToken) typeOfKeyword.clone(includeDiagnostics) : null,
            openParen != null ? (SyntaxToken) openParen.clone(includeDiagnostics) : null,
            types != null ? (SyntaxList1<SeparatedElement1<Expression>>) types.clone(includeDiagnostics) : null,
            closeParen != null ? (SyntaxToken) closeParen.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:155-160">
    @Override
    public boolean isLiteral() { return true; }

    @Override
    public ValueInfo literalValueInfo() { return null; }
    // </hand-written>
}
