// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node UnionOperator)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class UnionOperator extends QueryOperator {
    @Override public SyntaxKind kind() { return SyntaxKind.UnionOperator; }
    private final SyntaxToken unionKeyword;
    public SyntaxToken unionKeyword() { return unionKeyword; }
    private final SyntaxList1<NamedParameter> parameters;
    public SyntaxList1<NamedParameter> parameters() { return parameters; }
    private final SyntaxList1<SeparatedElement1<Expression>> expressions;
    public SyntaxList1<SeparatedElement1<Expression>> expressions() { return expressions; }

    /** Constructs a new instance of {@link UnionOperator}. */
    public UnionOperator(SyntaxToken unionKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<Expression>> expressions, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.unionKeyword = attach(unionKeyword);
        this.parameters = attach(parameters);
        this.expressions = attach(expressions);
        this.init();
    }
    public UnionOperator(SyntaxToken unionKeyword, SyntaxList1<NamedParameter> parameters, SyntaxList1<SeparatedElement1<Expression>> expressions) { this(unionKeyword, parameters, expressions, null); }

    @Override public int childCount() { return 3; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return unionKeyword; case 1: return parameters; case 2: return expressions; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "UnionKeyword"; case 1: return "Parameters"; case 2: return "Expressions"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.None; case 2: return CompletionHint.NonScalar; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitUnionOperator(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitUnionOperator(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new UnionOperator(unionKeyword != null ? (SyntaxToken) unionKeyword.clone(includeDiagnostics) : null,
            parameters != null ? (SyntaxList1<NamedParameter>) parameters.clone(includeDiagnostics) : null,
            expressions != null ? (SyntaxList1<SeparatedElement1<Expression>>) expressions.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
