// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node WhereClause)
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

public final class WhereClause extends SyntaxNode {
    @Override public SyntaxKind kind() { return SyntaxKind.WhereClause; }
    private final SyntaxToken whereKeyword;
    public SyntaxToken whereKeyword() { return whereKeyword; }
    private final Expression condition;
    public Expression condition() { return condition; }

    /** Constructs a new instance of {@link WhereClause}. */
    public WhereClause(SyntaxToken whereKeyword, Expression condition, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.whereKeyword = attach(whereKeyword);
        this.condition = attach(condition);
        this.init();
    }
    public WhereClause(SyntaxToken whereKeyword, Expression condition) { this(whereKeyword, condition, null); }

    @Override public int childCount() { return 2; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return whereKeyword; case 1: return condition; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "WhereKeyword"; case 1: return "Condition"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Keyword; case 1: return CompletionHint.Boolean; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitWhereClause(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitWhereClause(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new WhereClause(whereKeyword != null ? (SyntaxToken) whereKeyword.clone(includeDiagnostics) : null,
            condition != null ? (Expression) condition.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }
}
