// Ported from: src/Kusto.Language/Syntax/CodeGen/GeneratedSyntaxNodes.tt (node WildcardedName)
// Ported from: src/Kusto.Language/Syntax/SyntaxNode.cs
// Upstream: microsoft/Kusto-Query-Language @ 9d95a2d5bb085d151f14e88e07b703755fd914e1
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Microsoft Corporation. All rights reserved.
// Upstream license: Apache-2.0. This file is GENERATED by kusto-language-generator; do not edit outside <hand-written> regions.
package org.graylog.kusto.language.syntax;

import java.util.List;

import org.graylog.kusto.language.Diagnostic;
import org.graylog.kusto.language.editor.CompletionHint;

// <hand-written-imports>
// </hand-written-imports>

public final class WildcardedName extends Name {
    @Override public SyntaxKind kind() { return SyntaxKind.WildcardedName; }
    private final SyntaxToken pattern;
    public SyntaxToken pattern() { return pattern; }

    /** Constructs a new instance of {@link WildcardedName}. */
    public WildcardedName(SyntaxToken pattern, List<Diagnostic> diagnostics) {
        super(diagnostics);
        this.pattern = attach(pattern);
        this.init();
    }
    public WildcardedName(SyntaxToken pattern) { this(pattern, null); }

    @Override public int childCount() { return 1; }
    @Override public SyntaxElement getChild(int index) { switch (index) { case 0: return pattern; default: throw new IndexOutOfBoundsException(); } }
    @Override public String getName(int index) { switch (index) { case 0: return "Pattern"; default: throw new IndexOutOfBoundsException(); } }
    @Override protected int getCompletionHintCore(int index) { switch (index) { case 0: return CompletionHint.Syntax; default: return CompletionHint.Inherit; } }
    @Override public void accept(SyntaxVisitor visitor) { visitor.visitWildcardedName(this); }
    @Override public <TResult> TResult accept(SyntaxVisitor1<TResult> visitor) { return visitor.visitWildcardedName(this); }
    @Override @SuppressWarnings("unchecked") protected SyntaxElement cloneCore(boolean includeDiagnostics) {
        return new WildcardedName(pattern != null ? (SyntaxToken) pattern.clone(includeDiagnostics) : null,
            includeDiagnostics ? this.syntaxDiagnostics() : null);
    }

    // <hand-written from="src/Kusto.Language/Syntax/SyntaxNode.cs:237-240">
    @Override
    public String simpleName() { return this.pattern().valueText(); }
    // </hand-written>
}
